/*
 * Decompiled with CFR 0.152.
 */
package com.gremath.content;

import com.gremath.content.Doc;
import com.gremath.content.Enrich;
import com.gremath.content.TopicContent;
import com.gremath.model.Lesson;
import com.gremath.model.Topic;
import java.util.List;

public class AlgebraContent
implements TopicContent {
    @Override
    public Topic build() {
        Topic t = new Topic("algebra", "Algebra: Linear & Quadratic Equations", "Letters that stand for unknown numbers: building and solving linear equations, pairs of equations, quadratics, and the identities that make algebra fast.", "BOTH", 5);
        t.addLesson(new Lesson("1. Why letters? The idea of a variable", "<p>In algebra a letter like <strong>x</strong> is just a <em>placeholder for a number we don't know yet</em>. An equation is a balance scale: whatever is on the left equals whatever is on the right.</p>" + Doc.analogy("Picture a see-saw that is perfectly level. The two sides weigh the same. As long as you do the <em>same thing to both sides</em> (add, subtract, multiply, divide), it stays balanced \u2014 that's the one golden rule of solving equations.") + Doc.example("A mystery box", "\u201cI think of a number, add 7, and get 11.\u201d As an equation: x + 7 = 11. To find x, undo the +7 by subtracting 7 from <em>both</em> sides: x = 4.") + Doc.key("Golden rule: do the same operation to both sides to keep the equation balanced.") + Doc.recap("A variable is an unknown number. An equation balances two sides; keep it balanced while solving."), 1));
        t.addLesson(new Lesson("2. Solving linear equations", "<p>A <strong>linear equation</strong> has the variable to the first power only (no x\u00b2). To solve, peel away everything around x using <em>opposite</em> operations.</p><p>Think of equation solving as two goals: keep the balance true, and slowly isolate x. Every move must happen on both sides, otherwise the equality breaks.</p><h4>Order of undoing</h4>" + Doc.steps("Move the plain numbers to one side (undo + and \u2212).", "Move the multiplier off x (undo \u00d7 and \u00f7).", "Read off x, then plug it back to check.") + Doc.example("Solve 3x \u2212 7 = 11", "Add 7 to both sides: 3x = 18. Divide both sides by 3: x = <strong>6</strong>. Check: 3(6) \u2212 7 = 18 \u2212 7 = 11 \u2713") + "<h4>Fractions in linear equations</h4><p>If fractions appear, first clear denominators by multiplying both sides by the LCM of denominators.</p>" + Doc.example("Solve x/3 + 2 = 7", "Subtract 2: x/3 = 5. Multiply by 3: x = <strong>15</strong>.") + "<h4>Variables on both sides</h4>" + Doc.example("Solve 5x + 9 = 2x + 24", "Move x-terms together: 5x \u2212 2x = 24 \u2212 9 \u2192 3x = 15 \u2192 x = <strong>5</strong>.") + Doc.analogy("Undoing is like taking off shoes and socks: you remove them in the reverse order you put them on. Whatever was done <em>last</em> to x, undo it <em>first</em>.") + Doc.warn("When you multiply or divide both sides, do it to <em>every</em> term, not just one.") + Doc.tip("After solving, do a 10-second substitution check. It catches sign mistakes immediately.") + Doc.recap("Isolate x by undoing operations in reverse, doing the same to both sides. For fractions, clear denominators first; always verify."), 2));
        t.addLesson(new Lesson("3. Two equations, two unknowns", "<p>If a puzzle has two unknowns (say x and y), you need <strong>two</strong> equations to pin them down. Two popular methods:</p><h4>Substitution</h4><p>Solve one equation for a letter, then put that expression into the other.</p><h4>Elimination</h4><p>Add or subtract the equations so one letter cancels.</p>" + Doc.example("2x + 3y = 12 and x = 3", "Substitute x = 3 into the first: 2(3) + 3y = 12 \u2192 6 + 3y = 12 \u2192 3y = 6 \u2192 y = <strong>2</strong>.") + Doc.analogy("Two clues, two suspects: each clue alone leaves doubt, but together they reveal exactly who's who. One equation can't fix two unknowns on its own.") + Doc.tip("Pick the method that needs the least work: if one variable is already alone (like x = 3), substitution is instant.") + Doc.recap("n unknowns need n equations. Use substitution or elimination to reduce to one variable."), 3));
        t.addLesson(new Lesson("4. Quadratic equations", "<p>A <strong>quadratic</strong> contains an x\u00b2 term and looks like <strong>ax\u00b2 + bx + c = 0</strong>. It usually has <em>two</em> answers (roots).</p><h4>Factoring \u2014 the fast way</h4><p>Rewrite it as two brackets multiplied together. Find two numbers that <em>multiply</em> to c and <em>add</em> to b.</p>" + Doc.example("Solve x\u00b2 \u2212 5x + 6 = 0", "Need two numbers that multiply to +6 and add to \u22125: that's \u22122 and \u22123. So (x \u2212 2)(x \u2212 3) = 0. A product is zero only if a bracket is zero, giving x = <strong>2</strong> or x = <strong>3</strong>.") + "<h4>The quadratic formula \u2014 always works</h4>" + Doc.formula("x = [ \u2212b \u00b1 \u221a(b\u00b2 \u2212 4ac) ] \u00f7 2a") + "<p>The part under the root, b\u00b2\u22124ac (the <em>discriminant</em>), tells you how many real answers exist: positive \u2192 two, zero \u2192 one, negative \u2192 none.</p>" + Doc.tip("Sum of the two roots = \u2212b/a, and product of the roots = c/a. These let you answer many questions without fully solving.") + Doc.recap("Quadratics have x\u00b2 and usually two roots. Factor when easy; otherwise use the formula."), 4));
        t.addLesson(new Lesson("5. Identities that save time", "<p>These patterns appear again and again \u2014 memorising them lets you expand or factor instantly.</p>" + Doc.formula("(a + b)\u00b2 = a\u00b2 + 2ab + b\u00b2") + Doc.formula("(a \u2212 b)\u00b2 = a\u00b2 \u2212 2ab + b\u00b2") + Doc.formula("a\u00b2 \u2212 b\u00b2 = (a + b)(a \u2212 b)") + Doc.analogy("(a+b)\u00b2 is the area of a square with side (a+b). It splits into a big square a\u00b2, a small square b\u00b2, and two equal rectangles ab \u2014 that's where the 2ab comes from.") + Doc.example("Use an identity", "If x + 1/x = 4, find x\u00b2 + 1/x\u00b2. Square both sides: (x + 1/x)\u00b2 = x\u00b2 + 2 + 1/x\u00b2 = 16, so x\u00b2 + 1/x\u00b2 = <strong>14</strong>.") + Doc.warn("(a + b)\u00b2 is <em>not</em> a\u00b2 + b\u00b2. The middle term 2ab is the most-forgotten piece in all of algebra.") + Doc.recap("Know the three core identities. They turn messy expansions and factorisations into one step."), 5));
        t.addLesson(new Lesson("6. Linear inequalities", "<p>An <strong>inequality</strong> uses &lt;, &gt;, \u2264 or \u2265 instead of =. It describes a <em>range</em> of answers rather than a single value. You solve it almost exactly like an equation \u2014 with one famous twist.</p>" + Doc.analogy("'=' is a single point on the number line; an inequality is a whole stretch of it, like saying 'you must be taller than 120 cm to ride' \u2014 many heights qualify, not just one.") + Doc.steps("Isolate x using the same balancing moves as for equations.", "If you multiply or divide both sides by a <strong>negative</strong> number, FLIP the inequality sign.", "Describe the answer as a range, e.g. x > 3.") + Doc.example("Solve 2x + 1 > 9", "Subtract 1: 2x > 8. Divide by 2: x > <strong>4</strong>. The smallest integer that works is 5.") + Doc.example("Solve \u22123x > 12 (the flip!)", "Divide by \u22123 and flip: x < \u22124. Forgetting to flip is the #1 inequality mistake.") + Doc.warn("Only flip the sign for multiplying/dividing by a negative \u2014 NOT for adding or subtracting.") + Doc.recap("Solve like an equation, but flip the sign when multiplying or dividing by a negative number."), 6));
        t.addQuestion(Doc.q("Solve: 3x - 7 = 11.", List.of("x = 6", "x = 4", "x = 5", "x = 9"), 0, "Add 7: 3x = 18, then divide by 3: x = 6.", "EASY"));
        t.addQuestion(Doc.q("The roots of x\u00b2 - 5x + 6 = 0 are:", List.of("2 and 3", "-2 and -3", "1 and 6", "-1 and -6"), 0, "Factor: (x-2)(x-3) = 0, so x = 2 or 3.", "EASY"));
        t.addQuestion(Doc.q("If x + 1/x = 4, then x\u00b2 + 1/x\u00b2 equals:", List.of("14", "16", "18", "12"), 0, "(x + 1/x)\u00b2 = x\u00b2 + 2 + 1/x\u00b2 = 16, so x\u00b2 + 1/x\u00b2 = 14.", "HARD"));
        t.addQuestion(Doc.q("For 2x + 3y = 12 and x = 3, find y.", List.of("1", "2", "3", "4"), 1, "2(3) + 3y = 12 \u2192 3y = 6 \u2192 y = 2.", "EASY"));
        t.addQuestion(Doc.q("The sum of the roots of 2x\u00b2 - 8x + 6 = 0 is:", List.of("4", "-4", "3", "8"), 0, "Sum of roots = -b/a = 8/2 = 4.", "MEDIUM"));
        String ref = Doc.reference("For step-by-step algebra see <em>Manhattan Prep GRE Algebra</em>; for CAT-level word problems and quadratics, <em>Sarvesh K. Verma \u2013 Quantum CAT</em> (Arihant) and <em>Nishit K. Sinha \u2013 Quantitative Aptitude for the CAT</em> (Pearson) are excellent.");
        String wp = "<p>Algebra word problems are about <strong>naming the unknown</strong> and writing the sentence as an equation.</p>" + Doc.steps("Let x stand for what you're asked to find (or the smallest unknown).", "Translate each phrase: 'is' \u2192 =, 'more than' \u2192 +, 'twice' \u2192 \u00d72, 'product' \u2192 \u00d7.", "Solve, then re-read the question to answer exactly what was asked.") + Doc.tip("For two unknowns, write two equations; for consecutive numbers use n, n+1, n+2 \u2026");
        Enrich.lesson(t, 0, "alg-variable", ref, wp);
        Enrich.lesson(t, 1, "alg-linear", ref, wp);
        Enrich.lesson(t, 2, "alg-simultaneous", ref, wp);
        Enrich.lesson(t, 3, "alg-quadratic", ref, wp);
        Enrich.lesson(t, 4, "alg-identities", ref, wp);
        Enrich.lesson(t, 5, "alg-inequalities", ref, wp);
        return t;
    }
}

