/*
 * Decompiled with CFR 0.152.
 */
package com.gremath.content;

import com.gremath.content.Doc;
import com.gremath.content.Enrich;
import com.gremath.content.TopicContent;
import com.gremath.model.Lesson;
import com.gremath.model.Topic;
import java.util.List;

public class AveragesContent
implements TopicContent {
    @Override
    public Topic build() {
        Topic t = new Topic("averages-mixtures", "Averages, Mixtures & Alligation", "Finding the \u201cmiddle\u201d value, what happens when you add or remove items, weighted averages for unequal groups, and the alligation shortcut for mixtures.", "BOTH", 4);
        t.addLesson(new Lesson("1. What is an average?", "<p>The <strong>average</strong> (or <em>mean</em>) is the single \u201cfair-share\u201d value you'd get if you spread everything out equally.</p>" + Doc.formula("Average = (sum of all the values) \u00f7 (how many values)") + Doc.analogy("Three friends have 4, 8 and 6 chocolates. If they pour them into one pile (18) and redistribute equally, each gets 6. So the average is 6 \u2014 the amount everyone would have if sharing were perfectly fair.") + Doc.example("Average of 4, 8, 10 and 14", "Sum = 4+8+10+14 = 36. Count = 4. Average = 36 \u00f7 4 = <strong>9</strong>.") + Doc.key("Flip the formula whenever you know the average: <strong>Total = average \u00d7 number of values.</strong> This \u2018total\u2019 idea unlocks most average problems.") + Doc.tip("The average always lands somewhere between the smallest and largest value \u2014 never outside that range. Use this to sanity-check answers.") + Doc.recap("Average = total \u00f7 count. And total = average \u00d7 count."), 1));
        t.addLesson(new Lesson("2. Adding or removing a value", "<p>Exam questions love to say \u201cthe average changes when one number is added/removed.\u201d The secret is to work with <strong>totals</strong>, not the averages directly.</p>" + Doc.example("Average of 5 numbers is 20. One number is removed and the average becomes 22. Find it.", "Original total = 20 \u00d7 5 = 100. After removing one, 4 numbers remain with total = 22 \u00d7 4 = 88. The removed number = 100 \u2212 88 = <strong>12</strong>.") + Doc.analogy("Think of the total as water in a tank. Removing a number pours some out; compare the tank level (total) before and after to see how much left.") + "<h4>Why an average shifts</h4><p>If you add a value <em>above</em> the current average, the average rises; add one <em>below</em> it, and the average falls. Add a value <em>equal</em> to the average and nothing changes.</p>" + Doc.tip("A new value pulls the average toward itself, like a magnet \u2014 but only a little if the group is already large.") + Doc.recap("Convert averages to totals, do the add/subtract on the totals, then convert back."), 2));
        t.addLesson(new Lesson("3. Weighted averages (unequal groups)", "<p>A plain average treats every value as equally important. But if a class has 30 boys and only 20 girls, the boys' average should count <em>more</em>. That's a <strong>weighted average</strong>.</p>" + Doc.formula("Weighted avg = (n\u2081\u00d7A\u2081 + n\u2082\u00d7A\u2082) \u00f7 (n\u2081 + n\u2082)") + Doc.analogy("Your final grade where the exam is worth more than homework is a weighted average \u2014 the heavier item tugs the result toward its own value.") + Doc.example("30 boys average 40 kg, 20 girls average 35 kg. Class average?", "Total weight = 30\u00d740 + 20\u00d735 = 1200 + 700 = 1900 kg. Total people = 50. Average = 1900 \u00f7 50 = <strong>38 kg</strong>. Notice it's closer to 40 than 35, because there are more boys.") + Doc.warn("Don't just average the two averages ((40+35)\u00f72 = 37.5). That's only correct if the groups are the <em>same size</em>.") + Doc.recap("Weight each average by its group size: multiply, add, then divide by the total count."), 3));
        t.addLesson(new Lesson("4. Mixtures and the alligation rule", "<p>Mixing two things of different price or strength to hit a target value is just a weighted average run backwards. <strong>Alligation</strong> gives the mixing ratio quickly.</p>" + Doc.formula("(quantity of cheap) : (quantity of dear) = (dear \u2212 mean) : (mean \u2212 cheap)") + "<p>Think of alligation as a shortcut for balancing total value. The target mean must lie between the two source values; otherwise the mixture is impossible.</p>" + Doc.analogy("To make lukewarm water, you mix hot and cold. The closer the target is to \u2018cold\u2019, the more cold water you need. Alligation measures exactly how much of each.") + Doc.example("Mix rice at 30/kg with rice at 45/kg to get a mixture at 40/kg. In what ratio?", "Cheap = 30, dear = 45, mean = 40.<br>Cheap : dear = (45\u221240) : (40\u221230) = 5 : 10 = <strong>1 : 2</strong>. So twice as much of the costlier rice (since 40 is nearer 45).") + Doc.example("Milk-water blend", "Pure milk has value 100%, water has 0%. For a 70% milk target:<br>water : milk = (100\u221270):(70\u22120) = 30:70 = <strong>3:7</strong>.") + "<h4>When quantities are asked</h4>" + Doc.steps("First find the ratio by alligation.", "Convert ratio parts to real quantities using the given total quantity.", "Check by recomputing the weighted average to verify the target mean.") + Doc.warn("Don't reverse the ratio by mistake: cheap side uses (dear-mean), dear side uses (mean-cheap).") + Doc.tip("The ingredient whose value is <em>closer</em> to the target is the one you use <em>more</em> of. Use this to check your ratio points the right way.") + Doc.recap("Alligation: distances from the mean give the mixing ratio (cross them over). Closer to target \u2192 used in larger amount."), 4));
        t.addLesson(new Lesson("5. Median and mode: other kinds of 'middle'", "<p>The average (mean) is only one way to describe a 'typical' value. Two more are very useful, especially when a few extreme values would distort the mean.</p><h4>Median \u2014 the middle value</h4><p>Line the numbers up in order; the <strong>median</strong> is the one in the middle. If there is an even count, average the two middle ones.</p>" + Doc.example("Median of 3, 7, 9, 12, 20", "Already in order; the middle (3rd of 5) is <strong>9</strong>.") + "<h4>Mode \u2014 the most common value</h4><p>The <strong>mode</strong> is the value that appears most often.</p>" + Doc.analogy("If you ask everyone's favourite ice-cream and 'vanilla' wins most votes, vanilla is the mode \u2014 the crowd favourite, not an 'average flavour'.") + Doc.warn("A single huge value (an outlier) can drag the mean far from the centre, but barely moves the median. That's why house prices are usually reported as a median.") + Doc.recap("Mean = balance point, Median = middle of the sorted list, Mode = most frequent value."), 5));
        t.addQuestion(Doc.q("The average of 4, 8, 10 and 14 is:", List.of("8", "9", "10", "12"), 1, "Sum = 36, count = 4, average = 9.", "EASY"));
        t.addQuestion(Doc.q("The average of 5 numbers is 20. If one number is removed the average becomes 22. The removed number is:", List.of("12", "10", "14", "8"), 0, "Total = 100. Remaining 4 sum to 88. Removed = 100 - 88 = 12.", "MEDIUM"));
        t.addQuestion(Doc.q("In what ratio must rice at 30/kg be mixed with rice at 45/kg to get a mixture at 40/kg?", List.of("1 : 1", "1 : 2", "2 : 1", "3 : 2"), 1, "By alligation: (45-40) : (40-30) = 5 : 10 = 1 : 2.", "MEDIUM"));
        t.addQuestion(Doc.q("A class of 30 boys averages 40 kg and 20 girls average 35 kg. The class average weight is:", List.of("37.5 kg", "38 kg", "38.5 kg", "37 kg"), 1, "Total = 30\u00d740 + 20\u00d735 = 1900; /50 = 38 kg (weighted average).", "MEDIUM"));
        String ref = Doc.reference("For more on averages and mixtures see <em>Manhattan Prep GRE Word Problems</em>, and for CAT <em>Arun Sharma \u2013 Quantitative Aptitude for the CAT</em> (averages &amp; alligation chapters) and <em>Nishit K. Sinha \u2013 Quantitative Aptitude for the CAT</em>.");
        String wp = "<p>Average word problems live and die by the rule <strong>total = average \u00d7 count</strong>.</p>" + Doc.steps("Convert every 'average' into a total (multiply by how many).", "Add or remove the totals as the story describes.", "Divide the final total by the final count to get the new average.") + Doc.tip("For mixtures, the cheaper/weaker ingredient sits further from the target \u2014 use alligation to get the ratio fast.");
        Enrich.lesson(t, 0, "avg-mean", ref, wp);
        Enrich.lesson(t, 1, "avg-change", ref, wp);
        Enrich.lesson(t, 2, "avg-weighted", ref, wp);
        Enrich.lesson(t, 3, "avg-alligation", ref, wp);
        Enrich.lesson(t, 4, "avg-median-mode", ref, wp);
        return t;
    }
}

