/*
 * Decompiled with CFR 0.152.
 */
package com.gremath.content;

import com.gremath.content.Doc;
import com.gremath.content.Enrich;
import com.gremath.content.TopicContent;
import com.gremath.model.Lesson;
import com.gremath.model.Topic;
import java.util.List;

public class CountingContent
implements TopicContent {
    @Override
    public Topic build() {
        Topic t = new Topic("permutations-combinations", "Permutations & Combinations", "Smart ways to count without listing everything: the multiplication principle, factorials, arrangements (order matters) and selections (order doesn't).", "BOTH", 8);
        t.addLesson(new Lesson("1. The counting (multiplication) principle", "<p>If you can do one thing in <strong>m</strong> ways and a second thing in <strong>n</strong> ways, then you can do both, one after the other, in <strong>m \u00d7 n</strong> ways.</p>" + Doc.analogy("You own 3 shirts and 2 pairs of trousers. Each shirt can pair with each trouser, so there are 3 \u00d7 2 = 6 different outfits. Drawing it as a tree, every shirt branch splits into 2 trouser branches.") + Doc.example("How many 2-digit codes from digits 1\u20139?", "First digit: 9 choices. Second digit: 9 choices. Total = 9 \u00d7 9 = <strong>81</strong> codes.") + Doc.tip("Whenever a task is a sequence of independent choices, multiply the number of options at each step.") + Doc.recap("Multiply the choices at each stage to count the total number of outcomes."), 1));
        t.addLesson(new Lesson("2. Factorials \u2014 counting arrangements", "<p>A <strong>factorial</strong>, written n!, multiplies every whole number from n down to 1. It counts the ways to arrange n different items in a row.</p>" + Doc.formula("n! = n \u00d7 (n\u22121) \u00d7 \u2026 \u00d7 2 \u00d7 1 &nbsp;&nbsp; and &nbsp;&nbsp; 0! = 1") + Doc.analogy("Seating 3 friends in 3 chairs: the first chair has 3 choices, the next has 2 left, the last has 1. That's 3 \u00d7 2 \u00d7 1 = 6 = 3! seating plans.") + Doc.example("Arrange 5 people in a row", "5! = 5 \u00d7 4 \u00d7 3 \u00d7 2 \u00d7 1 = <strong>120</strong> ways.") + Doc.warn("0! = 1 by definition (there's exactly one way to arrange nothing). It looks odd but keeps all the formulas working.") + Doc.recap("n! counts arrangements of n items. It grows extremely fast."), 2));
        t.addLesson(new Lesson("3. Permutations: when order matters", "<p>A <strong>permutation</strong> arranges r items chosen from n, where the <em>order counts</em> (first, second, third are different roles).</p>" + Doc.formula("nPr = n! \u00f7 (n \u2212 r)!") + Doc.analogy("Awarding Gold, Silver and Bronze to 3 of 8 runners. Who comes first vs third matters, so order counts \u2014 that's a permutation.") + Doc.example("3-digit numbers from 1\u20139, no repeats", "Pick and order 3 of 9: 9P3 = 9 \u00d7 8 \u00d7 7 = <strong>504</strong>.") + Doc.tip("A quick way: nPr = just multiply r numbers counting down from n (9P3 = 9\u00d78\u00d77). No need to compute the big factorials.") + Doc.recap("Permutations = ordered selections. nPr = n\u00d7(n\u22121)\u00d7\u2026 for r terms."), 3));
        t.addLesson(new Lesson("4. Combinations: when order doesn't matter", "<p>A <strong>combination</strong> chooses r items from n where the <em>order makes no difference</em> (a team is the same team however you list its members).</p>" + Doc.formula("nCr = n! \u00f7 [ r! \u00d7 (n \u2212 r)! ]") + "<p>Combinations answer questions like: choose, select, shortlist, committee, group, set. If names can be rearranged without creating a new outcome, it's combination.</p>" + Doc.analogy("Picking 2 friends to come to a movie. Choosing Asha then Ben is the same pair as Ben then Asha \u2014 order is irrelevant, so it's a combination.") + Doc.example("Choose 2 books from 6", "6C2 = (6 \u00d7 5) \u00f7 (2 \u00d7 1) = 30 \u00f7 2 = <strong>15</strong> ways.") + Doc.key("Order matters \u2192 permutation (nPr). Order doesn't \u2192 combination (nCr). Because we ignore order, nCr is always smaller than nPr by a factor of r!.") + "<h4>Useful identities</h4>" + Doc.formula("nCr = nC(n-r)") + Doc.formula("nCr = n-1C(r-1) + n-1Cr") + Doc.example("A trickier one \u2014 a committee of 3 from 4 men and 3 women, with exactly 2 men", "Choose 2 men from 4: 4C2 = 6. Choose 1 woman from 3: 3C1 = 3. Multiply (counting principle): 6 \u00d7 3 = <strong>18</strong>.") + Doc.example("At least one woman in committee of 3 from 4 men and 3 women", "Total committees = 7C3 = 35. Committees with no women = all men = 4C3 = 4. Required = 35 \u2212 4 = <strong>31</strong>.") + Doc.steps("Read language clues: if ranking/position exists, it's not combination.", "Convert constraints (exactly/at least/at most) into separate counts.", "Use complement method when 'at least one' appears.") + Doc.warn("Don't apply permutation formula to team-selection questions \u2014 that overcounts by r! times.") + Doc.recap("Combinations = unordered selections (nCr). Decide \u2018does order matter?\u2019 first, then pick the tool."), 4));
        t.addLesson(new Lesson("5. Circular permutations and repeated items", "<p>Some arrangement questions are not simple straight-line permutations. Two frequent twists are <strong>arranging around a circle</strong> and <strong>repeated objects</strong>.</p><h4>Circular arrangement</h4><p>When people sit around a round table, rotating everyone together does not create a new pattern.</p>" + Doc.formula("Ways to arrange n distinct items in a circle = (n \u2212 1)!") + "<h4>Repeated items</h4><p>If items repeat, divide by factorials of repeats to remove overcounting.</p>" + Doc.formula("Arrangements of n items with repeats a,b,c... = n! / (a!b!c!... )") + Doc.example("Arrange letters of LEVEL", "5 letters with repeats L(2), E(2), V(1): ways = 5!/(2!2!) = 120/4 = <strong>30</strong>.") + Doc.tip("Whenever two outcomes look the same after swapping identical items, you've overcounted. Divide by repeat factorials.") + Doc.recap("Round table \u2192 (n-1)!, repeated items \u2192 divide by repeat factorials."), 5));
        t.addQuestion(Doc.q("In how many ways can 5 people stand in a row?", List.of("25", "60", "120", "20"), 2, "5! = 120.", "EASY"));
        t.addQuestion(Doc.q("How many ways to choose 2 books from 6?", List.of("12", "15", "30", "20"), 1, "6C2 = 6\u00d75/2 = 15 (order doesn't matter).", "EASY"));
        t.addQuestion(Doc.q("How many 3-digit numbers can be formed from 1-9 with no repetition?", List.of("504", "729", "720", "84"), 0, "9P3 = 9\u00d78\u00d77 = 504 (order matters).", "MEDIUM"));
        t.addQuestion(Doc.q("A committee of 3 is chosen from 4 men and 3 women, with exactly 2 men. Number of ways:", List.of("12", "18", "9", "24"), 1, "Choose 2 men (4C2 = 6) and 1 woman (3C1 = 3): 6\u00d73 = 18.", "HARD"));
        String ref = Doc.reference("See <em>Manhattan Prep GRE General Word Problems</em> (counting chapter) and, for CAT depth, <em>Sarvesh K. Verma \u2013 Quantum CAT</em> and <em>Nishit K. Sinha \u2013 Quantitative Aptitude for the CAT</em>.");
        String wp = "<p>Counting word problems become easy when you identify whether it's a product, permutation, or combination.</p>" + Doc.steps("Break the task into stages and multiply options at each stage.", "Ask first: does order matter? If yes, permutation; if no, combination.", "Check restrictions (no repeats, at least one, exactly k) before final counting.") + Doc.tip("For group-selection with conditions, count each required piece separately and multiply.");
        Enrich.lesson(t, 0, "cnt-multiplication", ref, wp);
        Enrich.lesson(t, 1, "cnt-factorial", ref, wp);
        Enrich.lesson(t, 2, "cnt-permutation", ref, wp);
        Enrich.lesson(t, 3, "cnt-combination", ref, wp);
        Enrich.lesson(t, 4, "cnt-circular-repeat", ref, wp);
        return t;
    }
}

