/*
 * Decompiled with CFR 0.152.
 */
package com.gremath.content;

import com.gremath.content.Doc;
import com.gremath.content.Enrich;
import com.gremath.content.TopicContent;
import com.gremath.model.Lesson;
import com.gremath.model.Topic;
import java.util.List;

public class GeometryContent
implements TopicContent {
    @Override
    public Topic build() {
        Topic t = new Topic("geometry", "Geometry & Mensuration", "Shapes and the space they take up: angles, triangles and the Pythagoras rule, circles, and the area/volume formulas you'll use everywhere.", "BOTH", 6);
        t.addLesson(new Lesson("1. Lines and angles", "<p>An <strong>angle</strong> measures how much you turn. A full spin is 360\u00b0, a half turn is 180\u00b0 (a straight line), and a quarter turn is 90\u00b0 (a \u2018square corner\u2019, called a <em>right angle</em>).</p>" + Doc.analogy("Think of a clock's hands. From 12 to 3 the minute hand turns a quarter \u2014 90\u00b0. From 12 all the way round back to 12 is a full 360\u00b0.") + "<h4>Useful angle facts</h4><ul><li>Angles on a straight line add to <strong>180\u00b0</strong>.</li><li>Angles all the way around a point add to <strong>360\u00b0</strong>.</li><li>When two lines cross, opposite angles are <strong>equal</strong>.</li></ul>" + Doc.recap("Right angle = 90\u00b0, straight line = 180\u00b0, full turn = 360\u00b0. Angles on a line sum to 180\u00b0."), 1));
        t.addLesson(new Lesson("2. Triangles and the Pythagorean theorem", "<p>A <strong>triangle</strong> is a three-sided shape, and its three angles always add up to <strong>180\u00b0</strong> \u2014 no matter its shape.</p>" + Doc.analogy("Tear the three corners off any paper triangle and place them side by side: they always form a perfectly straight line (180\u00b0). Try it!") + Doc.example("Angles in ratio 1 : 2 : 3", "The parts add to 6, and they must total 180\u00b0, so one part = 30\u00b0. The angles are 30\u00b0, 60\u00b0 and <strong>90\u00b0</strong> \u2014 a right-angled triangle.") + "<h4>Area of a triangle</h4>" + Doc.formula("Area = \u00bd \u00d7 base \u00d7 height") + "<h4>The Pythagorean theorem (right triangles)</h4><p>For a triangle with a 90\u00b0 corner, the longest side (the <em>hypotenuse</em>, opposite the right angle) obeys a beautiful rule:</p>" + Doc.formula("a\u00b2 + b\u00b2 = c\u00b2 &nbsp; (c = hypotenuse)") + Doc.analogy("Build a square on each of the three sides. The two smaller squares' areas <em>exactly</em> fill the biggest square. That's Pythagoras in pictures.") + Doc.example("Legs 3 and 4", "c\u00b2 = 3\u00b2 + 4\u00b2 = 9 + 16 = 25, so c = \u221a25 = <strong>5</strong>. (3-4-5 is the most famous right triangle \u2014 worth memorising, along with 5-12-13.)") + Doc.recap("Triangle angles sum to 180\u00b0. Area = \u00bd\u00b7base\u00b7height. Right triangles: a\u00b2 + b\u00b2 = c\u00b2."), 2));
        t.addLesson(new Lesson("3. Circles", "<p>A <strong>circle</strong> is every point the same distance from a centre. That distance is the <strong>radius</strong> (r); all the way across through the centre is the <strong>diameter</strong> (d = 2r).</p><h4>Two key measurements</h4>" + Doc.formula("Distance around (circumference) = 2\u03c0r") + Doc.formula("Space inside (area) = \u03c0r\u00b2") + "<p>Here <strong>\u03c0</strong> (\u2018pi\u2019, about 3.14 or 22/7) is how many diameters fit around the rim \u2014 the same magic number for <em>every</em> circle.</p>" + Doc.analogy("Wrap a string once around a tin and straighten it out: it's always about 3.14 times the width of the tin. That ratio is \u03c0.") + Doc.example("Area with radius 7 (\u03c0 = 22/7)", "Area = (22/7) \u00d7 7 \u00d7 7 = 22 \u00d7 7 = <strong>154</strong>. Choosing 22/7 here is smart because the 7s cancel neatly.") + Doc.tip("Read carefully whether the question gives radius or diameter \u2014 mixing them up is the most common circle error.") + Doc.recap("r = radius, d = 2r. Circumference = 2\u03c0r, area = \u03c0r\u00b2, and \u03c0 \u2248 3.14 \u2248 22/7."), 3));
        t.addLesson(new Lesson("4. Areas and volumes you must know", "<p><strong>Area</strong> measures flat space (square units). <strong>Volume</strong> measures how much a solid holds (cubic units).</p><table><tr><th>Shape</th><th>Formula</th></tr><tr><td>Rectangle area</td><td>length \u00d7 width</td></tr><tr><td>Square area</td><td>side\u00b2</td></tr><tr><td>Triangle area</td><td>\u00bd \u00d7 base \u00d7 height</td></tr><tr><td>Circle area</td><td>\u03c0r\u00b2</td></tr><tr><td>Cuboid (box) volume</td><td>length \u00d7 width \u00d7 height</td></tr><tr><td>Cube volume</td><td>side\u00b3</td></tr><tr><td>Cylinder volume</td><td>\u03c0r\u00b2h</td></tr><tr><td>Sphere volume</td><td>(4/3)\u03c0r\u00b3</td></tr></table>" + Doc.analogy("Volume of a box = how many 1\u00d71\u00d71 sugar cubes fit inside. Stack length \u00d7 width on the floor, then pile up \u2018height\u2019 layers.") + Doc.example("Volume of a cube of side 4", "Volume = side\u00b3 = 4 \u00d7 4 \u00d7 4 = <strong>64</strong> cubic units.") + Doc.warn("Keep units consistent and mind the dimensions: area uses square units (cm\u00b2), volume uses cubic units (cm\u00b3).") + Doc.recap("Memorise the table. Area is flat (squared units); volume is 3-D (cubed units)."), 4));
        t.addLesson(new Lesson("5. Perimeter and circumference", "<p><strong>Perimeter</strong> is the distance all the way around the edge of a flat shape \u2014 like the length of fence you'd need to enclose it. For a circle this 'distance around' has a special name: <strong>circumference</strong>.</p>" + Doc.analogy("Imagine an ant walking once around the very edge of a shape and back to its start. The total distance it walks is the perimeter.") + "<table><tr><th>Shape</th><th>Perimeter</th></tr><tr><td>Rectangle</td><td>2 \u00d7 (length + width)</td></tr><tr><td>Square</td><td>4 \u00d7 side</td></tr><tr><td>Triangle</td><td>add all three sides</td></tr><tr><td>Circle (circumference)</td><td>2\u03c0r = \u03c0 \u00d7 diameter</td></tr></table>" + Doc.example("Fencing a garden 12 m by 8 m", "Perimeter = 2 \u00d7 (12 + 8) = 2 \u00d7 20 = <strong>40 m</strong> of fence.") + Doc.tip("Perimeter is a length (m, cm) \u2014 never square units. Area and perimeter are different questions!") + Doc.recap("Perimeter = distance around. Rectangle 2(l+w), square 4s, circle 2\u03c0r."), 5));
        t.addLesson(new Lesson("6. Coordinate geometry: points on a grid", "<p>The coordinate plane is a map made of two number lines: the <strong>x-axis</strong> (across) and the <strong>y-axis</strong> (up). A point is written (x, y) \u2014 how far across, then how far up.</p>" + Doc.analogy("Coordinates are like seats in a cinema: '3 along, 5 up' lands you on exactly one seat. (x, y) lands you on exactly one point.") + "<h4>Three key tools</h4>" + Doc.formula("Distance between (x\u2081,y\u2081) and (x\u2082,y\u2082) = \u221a[(x\u2082\u2212x\u2081)\u00b2 + (y\u2082\u2212y\u2081)\u00b2]") + Doc.formula("Midpoint = ( (x\u2081+x\u2082)/2 , (y\u2081+y\u2082)/2 )") + Doc.formula("Slope (steepness) = (y\u2082\u2212y\u2081) \u00f7 (x\u2082\u2212x\u2081)") + "<p>Slope tells direction and steepness: positive slope rises rightward, negative slope falls rightward, zero slope is horizontal, and undefined slope is vertical.</p>" + Doc.example("Distance from (0,0) to (3,4)", "\u221a[(3\u22120)\u00b2 + (4\u22120)\u00b2] = \u221a(9+16) = \u221a25 = <strong>5</strong> \u2014 it's just Pythagoras!") + Doc.example("Midpoint of (2, 6) and (8, 10)", "Midpoint = ((2+8)/2, (6+10)/2) = (5, 8). It's the exact middle of the segment.") + "<h4>Distance from origin shortcut</h4><p>For a point (x, y), distance from origin O(0,0) is simply \u221ax\u00b2+y\u00b2.</p>" + Doc.steps("Sketch the points quickly before calculating.", "Compute horizontal gap (\u0394x) and vertical gap (\u0394y) first.", "Use distance/slope/midpoint formula based on what the question asks.", "Check sign and reasonableness: distance is never negative.") + Doc.warn("Don't swap x and y differences. Keep order consistent in numerator/denominator for slope.") + Doc.tip("The distance formula is the Pythagorean theorem in disguise: the gap across and the gap up are the two legs.") + Doc.recap("Points are (x, y). Distance = Pythagoras, midpoint = average the coordinates, slope = rise \u00f7 run."), 6));
        t.addQuestion(Doc.q("The area of a triangle with base 10 and height 6 is:", List.of("60", "30", "16", "32"), 1, "Area = \u00bd \u00d7 10 \u00d7 6 = 30.", "EASY"));
        t.addQuestion(Doc.q("A right triangle has legs 3 and 4. Its hypotenuse is:", List.of("5", "6", "7", "\u221a7"), 0, "3\u00b2 + 4\u00b2 = 9 + 16 = 25, so hypotenuse = 5.", "EASY"));
        t.addQuestion(Doc.q("The area of a circle with radius 7 (use \u03c0 = 22/7) is:", List.of("154", "144", "44", "49"), 0, "Area = (22/7) \u00d7 7 \u00d7 7 = 154.", "MEDIUM"));
        t.addQuestion(Doc.q("The angles of a triangle are in ratio 1 : 2 : 3. The largest angle is:", List.of("60\u00b0", "90\u00b0", "120\u00b0", "100\u00b0"), 1, "Parts sum to 6 = 180\u00b0, so 1 part = 30\u00b0. Largest = 3\u00d730 = 90\u00b0.", "MEDIUM"));
        t.addQuestion(Doc.q("The volume of a cube with side 4 is:", List.of("16", "48", "64", "12"), 2, "Volume = side\u00b3 = 4\u00b3 = 64.", "EASY"));
        String ref = Doc.reference("For diagrams and proofs see <em>Manhattan Prep GRE Geometry</em>; for CAT mensuration and coordinate geometry, <em>Arun Sharma \u2013 Quantitative Aptitude for the CAT</em> and <em>Nishit K. Sinha</em> (Pearson) cover every formula with worked examples.");
        String wp = "<p>Geometry word problems are about turning a description (or picture) into the right formula.</p>" + Doc.steps("Sketch the shape and label what you know.", "Choose the formula that links the known and unknown (area, perimeter, Pythagoras, volume).", "Substitute, compute, and attach the correct unit (cm for length, cm\u00b2 for area, cm\u00b3 for volume).") + Doc.tip("A right angle almost always signals the Pythagorean theorem; 'around the edge' means perimeter, 'inside' means area.");
        Enrich.lesson(t, 0, "geo-angles", ref, wp);
        Enrich.lesson(t, 1, "geo-triangles", ref, wp);
        Enrich.lesson(t, 2, "geo-circles", ref, wp);
        Enrich.lesson(t, 3, "geo-area-volume", ref, wp);
        Enrich.lesson(t, 4, "geo-perimeter", ref, wp);
        Enrich.lesson(t, 5, "geo-coordinate", ref, wp);
        return t;
    }
}

