/*
 * Decompiled with CFR 0.152.
 */
package com.gremath.content;

import com.gremath.content.Doc;
import com.gremath.content.Enrich;
import com.gremath.content.TopicContent;
import com.gremath.model.Lesson;
import com.gremath.model.Topic;
import java.util.List;

public class NumberPropertiesContent
implements TopicContent {
    @Override
    public Topic build() {
        Topic t = new Topic("number-properties", "Number Properties & Divisibility", "Meet the building blocks of all maths: integers, factors, multiples, primes, even/odd rules, divisibility tricks, HCF, LCM and remainders \u2014 explained from scratch.", "BOTH", 1);
        t.addLesson(new Lesson("1. What is a number, really?", "<p>Numbers are just a way of <strong>counting and measuring</strong> the world. When you count apples (1, 2, 3\u2026) you are using <em>counting numbers</em>. Add zero and you get the <em>whole numbers</em>: 0, 1, 2, 3\u2026</p><h4>The number line</h4><p>Imagine a long ruler that stretches forever in both directions. The middle is 0. Numbers to the right get bigger (1, 2, 3\u2026) and numbers to the left get smaller than zero (\u22121, \u22122, \u22123\u2026). Those negative numbers are like steps <em>below</em> ground level in a building, while positive numbers are floors above ground.</p>" + Doc.analogy("A lift in a mall: the ground floor is <strong>0</strong>. Going up gives floor +1, +2, +3. Going to the basement gives floor \u22121, \u22122. Both directions are real \u2014 just opposite.") + "<h4>The family of integers</h4><p>Put the negatives, zero and the positives together and you get the <strong>integers</strong>:</p>" + Doc.formula("\u2026 \u22123, \u22122, \u22121, 0, 1, 2, 3 \u2026") + "<p>Integers are <em>whole</em> \u2014 they have no fractions or decimals. The number 5 is an integer; 2.5 and \u00bd are not.</p>" + Doc.key("Counting numbers \u2192 whole numbers (add 0) \u2192 integers (add the negatives). Zero is an integer, and it is neither positive nor negative.") + Doc.recap("Numbers help us count and measure. On the number line, right = bigger, left = smaller. Integers are the whole numbers together with their negatives."), 1));
        t.addLesson(new Lesson("2. Factors and multiples", "<p>This pair of ideas confuses many students, so let's make it crystal clear with toy blocks.</p><h4>Multiples \u2014 the \u201cskip counting\u201d family</h4><p>The <strong>multiples</strong> of a number are what you get when you keep adding it to itself (the times-table). Multiples of 3 are 3, 6, 9, 12, 15\u2026 They go on forever and are always <em>as big as or bigger</em> than the number.</p>" + Doc.analogy("Multiples are like the stops a bus makes if it only stops every 3 streets: street 3, 6, 9, 12\u2026 it will never stop at street 7.") + "<h4>Factors \u2014 the \u201cwho can share it\u201d family</h4><p>A <strong>factor</strong> of a number divides it exactly, with <em>nothing left over</em>. Factors are always <em>as small as or smaller</em> than the number.</p>" + Doc.example("Factors of 12", "Which numbers divide 12 with no remainder? 1, 2, 3, 4, 6 and 12. So 12 has <span class='big-num'>six</span> factors. Notice they come in pairs that multiply to 12: (1,12), (2,6), (3,4).") + Doc.analogy("Factors answer: \u201cCan I share 12 sweets equally among this many friends?\u201d Among 3 friends? Yes, 4 each. Among 5 friends? No \u2014 someone misses out, so 5 is not a factor of 12.") + Doc.tip("Mix them up? Remember: <strong>F</strong>actors are <strong>F</strong>ewer (they stop, and are \u2264 the number). Multiples are many (they never stop).") + Doc.warn("1 is a factor of <em>every</em> number, and every number is a factor of itself.") + Doc.recap("Multiples = the times-table (3, 6, 9\u2026, never ending). Factors = numbers that divide exactly (small, and they stop)."), 2));
        t.addLesson(new Lesson("3. Prime and composite numbers", "<p>Some numbers can be broken into smaller equal groups; some stubbornly cannot. That single idea splits numbers into <strong>primes</strong> and <strong>composites</strong>.</p><h4>Prime numbers</h4><p>A <strong>prime number</strong> has <em>exactly two</em> factors: 1 and itself. The first few are 2, 3, 5, 7, 11, 13, 17, 19\u2026</p>" + Doc.analogy("A prime number of LEGO bricks can only be laid out as a single straight line. 7 bricks can't make a neat rectangle (other than 1\u00d77) \u2014 that's what makes 7 prime.") + Doc.key("<strong>2 is the only even prime number.</strong> Every other even number can be divided by 2, so it has an extra factor.") + "<h4>Composite numbers</h4><p>A <strong>composite number</strong> has <em>more than two</em> factors \u2014 it can be built by multiplying smaller numbers. 12 = 3\u00d74, so 12 is composite.</p>" + Doc.warn("The number <strong>1 is special</strong>: it has only one factor (itself), so it is <em>neither prime nor composite</em>.") + "<h4>How to test if a number is prime</h4>" + Doc.steps("Try dividing it by the small primes 2, 3, 5, 7, 11\u2026", "You only need to test primes up to the square root of the number.", "If none divide it exactly, it is prime.") + Doc.example("Is 91 prime?", "\u221a91 is about 9.5, so test primes up to 9: 2, 3, 5, 7. It fails 2, 3 and 5, but 91 = 7\u00d713. Since 7 divides it, <strong>91 is composite</strong>, not prime (a classic trap!).") + Doc.recap("Prime = exactly 2 factors. Composite = more than 2 factors. 1 is neither, and 2 is the only even prime."), 3));
        t.addLesson(new Lesson("4. Even & odd \u2014 rules that save time", "<p>An <strong>even</strong> number can be split into two equal whole groups (it ends in 0, 2, 4, 6, 8). An <strong>odd</strong> number always has one left over (ends in 1, 3, 5, 7, 9).</p>" + Doc.analogy("Even = everyone gets a partner for a dance. Odd = one person is always left standing alone.") + "<h4>The add/subtract rules</h4>" + Doc.formula("even \u00b1 even = even &nbsp;&nbsp; odd \u00b1 odd = even &nbsp;&nbsp; even \u00b1 odd = odd") + "<p>Two odds make an even (the two \u201cleftovers\u201d pair up). Mixing one odd with one even leaves the odd one out.</p><h4>The multiply rules</h4>" + Doc.formula("even \u00d7 anything = even &nbsp;&nbsp; odd \u00d7 odd = odd") + Doc.tip("For multiplication, you only get an <strong>odd</strong> answer when <em>every</em> number being multiplied is odd. A single even factor makes the whole product even.") + Doc.example("Quick check", "Is 3 \u00d7 5 \u00d7 7 \u00d7 8 odd or even? There's an 8 (even) in the mix, so the answer is <strong>even</strong> \u2014 no need to multiply it all out.") + Doc.recap("Adding: like + like = even, different = odd. Multiplying: one even factor makes it even."), 4));
        t.addLesson(new Lesson("5. Divisibility rules (the shortcuts)", "<p>Divisibility rules let you check if one number divides another <em>without</em> doing the full division. They are huge time-savers in exams.</p><table><tr><th>Divisible by</th><th>Quick test</th><th>Example</th></tr><tr><td>2</td><td>Last digit is even (0,2,4,6,8)</td><td>134 \u2713</td></tr><tr><td>3</td><td>Digits add up to a multiple of 3</td><td>132 \u2192 1+3+2=6 \u2713</td></tr><tr><td>4</td><td>Last two digits form a multiple of 4</td><td>516 \u2192 16 \u2713</td></tr><tr><td>5</td><td>Ends in 0 or 5</td><td>245 \u2713</td></tr><tr><td>6</td><td>Passes both the 2 and 3 tests</td><td>132 \u2713</td></tr><tr><td>8</td><td>Last three digits form a multiple of 8</td><td>1240 \u2192 240 \u2713</td></tr><tr><td>9</td><td>Digits add up to a multiple of 9</td><td>513 \u2192 5+1+3=9 \u2713</td></tr><tr><td>10</td><td>Ends in 0</td><td>90 \u2713</td></tr><tr><td>11</td><td>Alternating digit sum is 0 or a multiple of 11</td><td>2728 \u2192 (8\u22122+7\u22122)=11 \u2713</td></tr></table>" + Doc.analogy("The digit-sum rule for 3 and 9 is like checking if a bag of coins is shareable by counting the coins, not their exact value \u2014 surprisingly, just adding the digits works!") + Doc.example("Is 738 divisible by 6?", "Test 2: last digit 8 is even \u2713. Test 3: 7+3+8 = 18, a multiple of 3 \u2713. Passes both, so <strong>yes, 738 is divisible by 6</strong>.") + Doc.tip("If digits add to a multiple of 9 they also add to a multiple of 3, so every number divisible by 9 is automatically divisible by 3.") + Doc.recap("Learn the tests for 2, 3, 4, 5, 9 and 11 \u2014 they cover most exam questions."), 5));
        t.addLesson(new Lesson("6. Prime factorisation, HCF & LCM", "<p>Every whole number bigger than 1 can be written as a unique product of primes. This is called <strong>prime factorisation</strong> \u2014 the number's \u201cDNA\u201d.</p>" + Doc.example("Prime factorisation of 360", "Keep splitting into factors until only primes remain:<br>360 = 36 \u00d7 10 = (4\u00d79) \u00d7 (2\u00d75) = 2\u00d72\u00d73\u00d73\u00d72\u00d75.<br>Tidied up: <span class='big-num'>360 = 2\u00b3 \u00d7 3\u00b2 \u00d7 5</span>.") + "<h4>Why prime factorisation is so useful</h4><p>Once numbers are written in prime powers, many hard-looking questions become simple: HCF, LCM, factor count, divisibility, and even simplification of fractions.</p>" + Doc.steps("Write each number in prime-power form (like 2\u00b3\u00d73\u00b2).", "For HCF, keep only common primes with the <strong>smaller</strong> powers.", "For LCM, keep every prime seen with the <strong>larger</strong> powers.") + "<h4>Counting all the factors (a magic shortcut)</h4><p>Take the powers in the prime factorisation, add 1 to each, and multiply:</p>" + Doc.formula("number of factors = (3+1)(2+1)(1+1) = 4\u00d73\u00d72 = 24 factors of 360") + Doc.example("Count factors of 72 quickly", "72 = 2\u00b3 \u00d7 3\u00b2. So factors = (3+1)(2+1) = 4\u00d73 = <strong>12</strong>.") + "<h4>HCF \u2014 Highest Common Factor</h4><p>The biggest number that divides two numbers. Think: the largest equal group both can form.</p>" + Doc.analogy("You have 12 red and 18 blue balloons and want identical bunches with no balloons left over. The biggest bunch size is the HCF of 12 and 18, which is 6.") + Doc.example("HCF of 84 and 126", "84 = 2\u00b2\u00d73\u00d77, 126 = 2\u00d73\u00b2\u00d77. Common primes with smaller powers: 2\u00d73\u00d77 = <strong>42</strong>.") + "<h4>LCM \u2014 Lowest Common Multiple</h4><p>The smallest number that both numbers divide into. Think: when two repeating events line up again.</p>" + Doc.analogy("One bell rings every 12 minutes, another every 18. They ring together again after the LCM of 12 and 18 = 36 minutes.") + Doc.example("LCM of 84 and 126", "Take all primes with larger powers: 2\u00b2\u00d73\u00b2\u00d77 = 4\u00d79\u00d77 = <strong>252</strong>.") + Doc.key("For any two numbers: <strong>HCF \u00d7 LCM = the product of the two numbers.</strong> So if you know three of these, you can always find the fourth.") + Doc.warn("Don't mix the power rule: HCF uses smaller powers, LCM uses larger powers.") + Doc.tip("Story shortcut: 'largest equal groups' \u2192 HCF, 'first common time/size' \u2192 LCM.") + Doc.recap("Break numbers into primes. Add-1-and-multiply the powers to count factors. HCF = biggest shared factor; LCM = first shared multiple; and HCF\u00d7LCM = product of the numbers."), 6));
        t.addLesson(new Lesson("7. Remainders made simple", "<p>When a number doesn't divide evenly, the bit left over is the <strong>remainder</strong>.</p>" + Doc.analogy("Share 17 sweets among 5 kids: each gets 3 (that's 15 sweets) and <strong>2 sweets are left over</strong>. The remainder is 2.") + Doc.formula("Dividend = Divisor \u00d7 Quotient + Remainder &nbsp; (e.g. 17 = 5\u00d73 + 2)") + "<p>The remainder is always smaller than the divisor \u2014 if it weren't, you could share out one more.</p>" + Doc.tip("To find the remainder when a big power is divided by a small number, look for a pattern. Powers of a number cycle through the same few remainders.") + Doc.example("Remainder of 2\u00b9\u2070 \u00f7 3", "Notice 2 leaves remainder \u22121 (same as 2) when divided by 3, and (\u22121) raised to an even power is +1. So 2\u00b9\u2070 leaves remainder <strong>1</strong>.") + Doc.recap("Remainder = what's left after fair sharing, and it's always less than the divisor."), 7));
        t.addLesson(new Lesson("8. Units digit of powers (cyclicity)", "<p>Exams love to ask for the <strong>last digit</strong> of a giant power like 7\u00b9\u2070\u2070. You never compute the whole thing \u2014 you use the fact that the units digit <em>repeats in a short cycle</em>.</p>" + Doc.analogy("The units digit is like the second hand of a clock: it loops through the same pattern over and over. Find the loop length, then jump to the right spot.") + "<h4>The cycles</h4><table><tr><th>Ends in</th><th>Cycle of units digits</th><th>Length</th></tr><tr><td>2</td><td>2, 4, 8, 6</td><td>4</td></tr><tr><td>3</td><td>3, 9, 7, 1</td><td>4</td></tr><tr><td>7</td><td>7, 9, 3, 1</td><td>4</td></tr><tr><td>8</td><td>8, 4, 2, 6</td><td>4</td></tr><tr><td>4</td><td>4, 6</td><td>2</td></tr><tr><td>9</td><td>9, 1</td><td>2</td></tr><tr><td>0,1,5,6</td><td>always 0,1,5,6</td><td>1</td></tr></table>" + Doc.steps("Look only at the base's units digit.", "Find the cycle length L (4, 2 or 1 from the table).", "Divide the exponent by L; the remainder tells you which position in the cycle (a remainder of 0 means the last one).") + Doc.example("Units digit of 7\u00b9\u2070\u2070", "Base ends in 7 \u2192 cycle 7,9,3,1 (length 4). 100 \u00f7 4 leaves remainder 0 \u2192 the 4th in the cycle = <strong>1</strong>.") + Doc.key("Numbers ending in 0, 1, 5 or 6 keep the same units digit for every power \u2014 the easiest case.") + Doc.recap("Use the 4/2/1-long cycle of the base's units digit; the exponent's remainder picks the position."), 8));
        t.addQuestion(Doc.q("Which of the following is a prime number?", List.of("51", "57", "61", "91"), 2, "61 has no divisor other than 1 and 61. 51 = 3\u00d717, 57 = 3\u00d719, 91 = 7\u00d713.", "EASY"));
        t.addQuestion(Doc.q("If n is an odd integer, which expression is always even?", List.of("n + 2", "n\u00b2", "3n", "n + 1"), 3, "odd + 1 = even. n+2 stays odd, n\u00b2 of an odd is odd, and 3\u00d7odd is odd.", "EASY"));
        t.addQuestion(Doc.q("How many positive factors does 72 have?", List.of("6", "8", "12", "10"), 2, "72 = 2\u00b3 \u00d7 3\u00b2, so number of factors = (3+1)(2+1) = 12.", "MEDIUM"));
        t.addQuestion(Doc.q("Which number is divisible by both 3 and 4?", List.of("114", "132", "146", "158"), 1, "132: digits 1+3+2=6 (divisible by 3) and last two digits 32 is a multiple of 4. So it is divisible by 12.", "MEDIUM"));
        t.addQuestion(Doc.q("What is the remainder when 2^10 is divided by 3?", List.of("0", "1", "2", "3"), 1, "2 \u2261 -1 (mod 3), so 2^10 \u2261 (-1)^10 = 1 (mod 3).", "MEDIUM"));
        t.addQuestion(Doc.q("The HCF of two numbers is 6 and their LCM is 60. If one number is 12, the other is:", List.of("30", "24", "18", "36"), 0, "Product = HCF \u00d7 LCM = 6 \u00d7 60 = 360. Other = 360 / 12 = 30.", "MEDIUM"));
        String ref = Doc.reference("These ideas are covered in <em>Manhattan Prep GRE Number Properties</em>, and for CAT in <em>Nishit K. Sinha \u2013 Quantitative Aptitude for the CAT</em> (Pearson) and <em>Arun Sharma \u2013 How to Prepare for Quantitative Aptitude for the CAT</em> (McGraw\u2011Hill).");
        String wpGeneric = "<p>Number-property word problems hide a divisibility, HCF or LCM question inside a story.</p>" + Doc.steps("Translate the story: 'largest equal groups / biggest tile' \u2192 <strong>HCF</strong>; 'events happening together again / smallest common length' \u2192 <strong>LCM</strong>.", "'Left over after sharing' \u2192 <strong>remainder</strong>.", "Write the numbers, find their prime factors, then apply the right tool.") + Doc.tip("If the answer must be a whole number of people/tiles/days, you are almost always using HCF or LCM.");
        Enrich.lesson(t, 0, "np-numbers", ref, wpGeneric);
        Enrich.lesson(t, 1, "np-factors-multiples", ref, wpGeneric);
        Enrich.lesson(t, 2, "np-primes", ref, wpGeneric);
        Enrich.lesson(t, 3, "np-even-odd", ref, wpGeneric);
        Enrich.lesson(t, 4, "np-divisibility", ref, wpGeneric);
        Enrich.lesson(t, 5, "np-hcf-lcm", ref, wpGeneric);
        Enrich.lesson(t, 6, "np-remainders", ref, wpGeneric);
        Enrich.lesson(t, 7, "np-units-digit", ref, wpGeneric);
        return t;
    }
}

