/*
 * Decompiled with CFR 0.152.
 */
package com.gremath.content;

import com.gremath.content.Doc;
import com.gremath.content.TopicContent;
import com.gremath.model.Lesson;
import com.gremath.model.Topic;
import java.util.List;

public class PercentagesContent
implements TopicContent {
    private static final String STRAT_MEANING = "<p>Word problems on percentages usually hide a simple \u2018part out of whole\u2019 question. Use this routine:</p>" + Doc.steps("<strong>Spot the whole.</strong> Find the total the percent is measured against (marks out of, students out of, etc.).", "<strong>Spot the part.</strong> Identify the smaller amount being compared to the whole.", "<strong>Divide and \u00d7100.</strong> Percent = (part \u00f7 whole) \u00d7 100.", "<strong>Sense-check.</strong> A part smaller than the whole must give under 100%.") + Doc.tip("Watch for the word <em>\u2018NOT\u2019</em>: if 15% are red, then 85% are not red. Subtract from 100%.");
    private static final String STRAT_PERCENT_OF = "<p>These problems give a percent and a whole and ask for the part \u2014 or run it backwards.</p>" + Doc.steps("Translate the words: <em>\u2018of\u2019 = \u00d7</em>, <em>\u2018is\u2019 = =</em>.", "Forward (part unknown): part = (percent \u00f7 100) \u00d7 whole.", "Backward (whole unknown): find 1% first (divide the part by the percent), then \u00d7100.", "Underline what is actually asked \u2014 discount <em>amount</em> vs final <em>price</em> are different!") + Doc.tip("Build awkward percents from easy pieces: 35% = 10%+10%+10%+5%. And 12.5% = 1/8, 37.5% = 3/8.");
    private static final String STRAT_CHANGE = "<p>Increase/decrease problems compare a new value with an old one.</p>" + Doc.steps("Identify the <strong>original</strong> value \u2014 it is always the base (the denominator).", "% change = (new \u2212 old) \u00f7 old \u00d7 100.", "To apply a change, use a multiplier: +20% \u2192 \u00d71.20, \u221220% \u2192 \u00d70.80.", "Given the result and asked for the original? Divide by the multiplier, don't subtract the percent.") + Doc.warn("\u2018x% more\u2019 and \u2018x% less\u2019 are not symmetric \u2014 the base changes, so going up then down by the same percent does not return to the start.");
    private static final String STRAT_SUCCESSIVE = "<p>When two or more changes happen one after another, never just add the percents.</p>" + Doc.steps("Turn each change into a multiplier (e.g. +25% \u2192 1.25, \u221210% \u2192 0.90).", "Multiply all the multipliers together.", "Subtract 1 and \u00d7100 to read the single equivalent percentage change.", "For value questions, multiply the starting amount by the combined multiplier.") + Doc.tip("Quick formula for two changes: net% = a + b + ab/100 (use signed values, so a decrease is negative).");

    @Override
    public Topic build() {
        Topic t = new Topic("percentages", "Percentages", "The language of \u201cout of 100\u201d: converting percentages, finding a percent of a number, percentage increase/decrease, and the famous successive-change trap.", "BOTH", 2);
        t.addLesson(new Lesson("1. What does \u201cpercent\u201d mean?", "<p>The word <strong>percent</strong> literally means <em>\u201cper hundred\u201d</em> (<em>cent</em> = 100, like 100 cents in a dollar). So 40% just means <strong>40 out of every 100</strong>.</p>" + Doc.analogy("Imagine every quantity cut into 100 equal slices, like a giant pizza with 100 slices. 25% is 25 slices, 50% is half the pizza, 100% is the whole pizza.") + "<h4>Three ways to write the same thing</h4>" + Doc.formula("40% &nbsp;=&nbsp; 40/100 &nbsp;=&nbsp; 0.40") + "<p>To turn a percent into a decimal, divide by 100 (slide the dot two places left). To turn a decimal into a percent, multiply by 100 (slide the dot two places right).</p><h4>Friendly fractions worth memorising</h4><table><tr><th>Fraction</th><th>Percent</th></tr><tr><td>1/2</td><td>50%</td></tr><tr><td>1/4</td><td>25%</td></tr><tr><td>1/5</td><td>20%</td></tr><tr><td>1/8</td><td>12.5%</td></tr><tr><td>1/3</td><td>33\u2153%</td></tr><tr><td>1/10</td><td>10%</td></tr></table>" + Doc.tip("Knowing these by heart turns slow questions into instant ones. Seeing \u201c25% of something\u201d? Just take a quarter of it.") + Doc.recap("Percent = out of 100. Any percent is also a fraction (over 100) and a decimal."), 1, "percent-meaning", STRAT_MEANING));
        t.addLesson(new Lesson("2. Finding a percent of a number", "<p>The most common task: \u201cWhat is 15% of 240?\u201d The word <strong>\u201cof\u201d</strong> means <em>multiply</em>.</p>" + Doc.formula("x% of N = (x \u00f7 100) \u00d7 N") + Doc.example("15% of 240", "Method 1 (decimal): 0.15 \u00d7 240 = 36.<br>Method 2 (break it up): 10% of 240 = 24, and 5% is half of that = 12. Add: 24 + 12 = <strong>36</strong>.") + Doc.analogy("Finding 10% is like cutting a pizza into 10 equal slices and taking one \u2014 just move the decimal point one place left. 10% of 240 \u2192 24.0 \u2192 24.") + Doc.tip("Build any percent from easy pieces: <strong>10%</strong> (move the dot), <strong>5%</strong> (half of 10%), <strong>1%</strong> (move the dot twice). For 35%: 10%+10%+10%+5%.") + "<h4>Going backwards: the part is given</h4><p>\u201c12 is 20% of what number?\u201d If 20% is 12, then 1% is 12\u00f720 = 0.6, so 100% is 0.6\u00d7100 = <strong>60</strong>.</p>" + Doc.warn("Always ask \u201cpercent <em>of what</em>?\u201d The base (the \u201cwhole\u201d) is what 100% refers to. Choosing the wrong base is the #1 percentage mistake.") + Doc.recap("\u201cOf\u201d means multiply. To go backwards, find 1% first, then scale to 100%."), 2, "percent-of", STRAT_PERCENT_OF));
        t.addLesson(new Lesson("3. Percentage increase and decrease", "<p>Prices rise, populations grow, things go on sale. We measure such changes as a percent <em>of the starting amount</em>.</p>" + Doc.formula("% change = (new value \u2212 old value) \u00f7 old value \u00d7 100") + Doc.key("The denominator is always the <strong>original (old)</strong> value \u2014 the amount you started with.") + Doc.example("Price rises from 50 to 65", "Change = 65 \u2212 50 = 15. As a percent of the original 50: (15 \u00f7 50) \u00d7 100 = <strong>30% increase</strong>.") + Doc.example("A 20% discount on a 80 shirt", "20% of 80 = 16 off. New price = 80 \u2212 16 = <strong>64</strong>.") + "<h4>Why increase % and decrease % don't match</h4><p>Going from 80 up to 100 is a 25% rise, but going from 100 back down to 80 is only a 20% fall \u2014 <em>even though it's the same 20 difference</em>. The reason: the base changed!</p>" + Doc.analogy("Climbing from floor 80 to 100 is 20 floors out of 80 (a big chunk). Coming down is 20 floors out of 100 (a smaller chunk). Same steps, different starting point.") + Doc.tip("\u201cIncrease by 20%\u201d = multiply by 1.20. \u201cDecrease by 20%\u201d = multiply by 0.80. Turning changes into multipliers makes everything faster.") + Doc.recap("% change is measured against the original value. Up and down by the same number of units give different percentages because the base differs."), 3, "percent-change", STRAT_CHANGE));
        t.addLesson(new Lesson("4. Successive (back-to-back) changes", "<p>What if something changes twice \u2014 say a price goes up 25% and then drops 20%? You <strong>cannot</strong> just add and subtract the percents, because the second change acts on a <em>new</em> amount.</p>" + Doc.warn("+25% then \u221220% is <strong>not</strong> +5%. The second percent is taken from a bigger number, so the pieces don't cancel the way they look.") + "<h4>The reliable multiplier method</h4>" + Doc.steps("Turn each change into a multiplier (+25% \u2192 1.25, \u221220% \u2192 0.80).", "Multiply them together: 1.25 \u00d7 0.80 = 1.00.", "A multiplier of 1.00 means <strong>no net change</strong> (0%).") + Doc.example("Start with 100", "Up 25%: 100 \u2192 125. Down 20% of 125 = 25 off \u2192 100. Back to where we started \u2014 net change is <strong>0%</strong>, exactly as the multipliers predicted.") + "<h4>The quick formula</h4>" + Doc.formula("net% = a + b + (a \u00d7 b) \u00f7 100") + "<p>For +20% then +20%: 20 + 20 + (400\u00f7100) = 44% (not 40%).</p>" + Doc.tip("The multiplier method never lets you down and works for any number of changes \u2014 just keep multiplying.") + Doc.recap("For successive changes, multiply the multipliers. Adding percents is a trap."), 4, "percent-successive", STRAT_SUCCESSIVE));
        t.addQuestion(Doc.q("What is 15% of 240?", List.of("24", "36", "32", "40"), 1, "0.15 \u00d7 240 = 36 (or 10% = 24 plus 5% = 12).", "EASY"));
        t.addQuestion(Doc.q("A price rises from 50 to 65. What is the percentage increase?", List.of("15%", "25%", "30%", "23%"), 2, "Increase = 15 on a base of 50 = (15/50)\u00d7100 = 30%.", "EASY"));
        t.addQuestion(Doc.q("If a number is increased by 25% and then decreased by 20%, the net change is:", List.of("No change", "+5%", "-5%", "+45%"), 0, "Multipliers: 1.25 \u00d7 0.80 = 1.00, so there is no net change.", "MEDIUM"));
        t.addQuestion(Doc.q("60% of students passed. If 80 students failed, how many students are there in total?", List.of("160", "200", "240", "120"), 1, "Failures = 40% = 80, so 1% = 2, total = 200.", "MEDIUM"));
        t.addQuestion(Doc.q("A's salary is 20% more than B's. By what percent is B's salary less than A's?", List.of("20%", "25%", "16.67%", "10%"), 2, "If B = 100, A = 120. B is less by 20/120 = 16.67%.", "HARD"));
        return t;
    }
}

