/*
 * Decompiled with CFR 0.152.
 */
package com.gremath.content;

import com.gremath.content.Doc;
import com.gremath.content.Enrich;
import com.gremath.content.TopicContent;
import com.gremath.model.Lesson;
import com.gremath.model.Topic;
import java.util.List;

public class ProbabilityContent
implements TopicContent {
    @Override
    public Topic build() {
        Topic t = new Topic("probability", "Probability", "Measuring how likely something is: the basic fraction, the \u2018not\u2019 shortcut, and combining events with AND / OR.", "BOTH", 9);
        t.addLesson(new Lesson("1. What is probability?", "<p><strong>Probability</strong> is a number that says how likely an event is. It's simply a fraction:</p>" + Doc.formula("P(event) = (number of favourable outcomes) \u00f7 (total number of outcomes)") + Doc.analogy("Roll a fair die. There are 6 equally likely faces. Rolling a 4 is just 1 of those 6, so its probability is 1/6.") + "<p>Probability always sits between 0 and 1:</p><ul><li><strong>0</strong> = impossible (a die showing 7).</li><li><strong>1</strong> = certain (a die showing a number from 1 to 6).</li><li><strong>1/2</strong> = a 50-50 chance (a coin landing heads).</li></ul>" + Doc.example("Even number on a die", "Favourable outcomes {2, 4, 6} = 3. Total = 6. P = 3/6 = <strong>1/2</strong>.") + Doc.tip("If an answer comes out bigger than 1 or below 0, you've made a slip \u2014 probabilities can never leave the 0-to-1 range.") + Doc.recap("Probability = favourable \u00f7 total, always between 0 (impossible) and 1 (certain)."), 1));
        t.addLesson(new Lesson("2. The complement: probability of \u2018not\u2019", "<p>Sometimes it's easier to count what you <em>don't</em> want. Since something either happens or it doesn't, the two probabilities must add to 1.</p>" + Doc.formula("P(not A) = 1 \u2212 P(A)") + Doc.analogy("If there's a 30% chance of rain, there's automatically a 70% chance of no rain. The two add up to the whole 100%.") + Doc.example("At least one head in two coin tosses", "\u2018At least one\u2019 is fiddly to count directly, so use the complement. P(no heads) = P(tails, tails) = 1/2 \u00d7 1/2 = 1/4. So P(at least one head) = 1 \u2212 1/4 = <strong>3/4</strong>.") + Doc.tip("Whenever you see the phrase \u2018at least one\u2019, the complement trick is usually the fast route.") + Doc.recap("P(not A) = 1 \u2212 P(A). Great for \u2018at least one\u2019 questions."), 2));
        t.addLesson(new Lesson("3. Combining events: AND vs OR", "<p>Two key rules let you build bigger probabilities from smaller ones.</p><h4>AND \u2014 both happen (multiply)</h4><p>For <em>independent</em> events (one doesn't affect the other), multiply.</p>" + Doc.formula("P(A and B) = P(A) \u00d7 P(B)") + Doc.analogy("Two heads in a row: 1/2 for the first AND 1/2 for the second = 1/2 \u00d7 1/2 = 1/4. \u2018AND\u2019 narrows things down, so the chance gets smaller.") + "<p>If events are not independent, use conditional form instead:</p>" + Doc.formula("P(A and B) = P(A) \u00d7 P(B|A)") + "<h4>OR \u2014 either happens (add)</h4>" + Doc.formula("P(A or B) = P(A) + P(B) \u2212 P(A and B)") + "<p>We subtract the overlap so we don't count it twice.</p>" + Doc.example("Draw a card: a King or a Heart", "P(King) = 4/52, P(Heart) = 13/52, but the King of Hearts is in both, P(overlap) = 1/52. P(King or Heart) = 4/52 + 13/52 \u2212 1/52 = <strong>16/52 = 4/13</strong>.") + "<h4>Mutually exclusive shortcut</h4><p>If A and B cannot happen together, then overlap is zero and OR is just addition.</p>" + Doc.example("One die roll: probability of 1 or 2", "Events are disjoint, so P(1 or 2) = 1/6 + 1/6 = <strong>1/3</strong>.") + Doc.steps("Decide if the connector is AND or OR.", "For OR, check if overlap exists. If yes, subtract it once.", "For AND, check independence; if dependent, switch to conditional form.") + Doc.warn("\u2018AND\u2019 \u2192 multiply (chance shrinks). \u2018OR\u2019 \u2192 add (chance grows). Mixing these up is the most common probability error.") + Doc.recap("AND = multiply (independent events). OR = add, minus the overlap."), 3));
        t.addLesson(new Lesson("4. Conditional probability and Bayes intuition", "<p><strong>Conditional probability</strong> means updating chances after learning new information.</p>" + Doc.formula("P(A | B) = P(A and B) / P(B)") + "<p>The phrase <em>given B</em> means your universe has changed. You are no longer counting all outcomes, only outcomes where B is true.</p>" + Doc.analogy("If you know a card is red, the chance that it's a king changes. You are no longer choosing from all 52 cards, only from the 26 red cards.") + Doc.example("A card is known to be a face card. Probability it is a king?", "Face cards are J, Q, K: 12 cards total. Kings among them: 4. So P(king | face) = 4/12 = <strong>1/3</strong>.") + "<h4>Table method for reliability</h4>" + Doc.steps("Create a 2x2 table (A / not-A vs B / not-B) with counts.", "Fill known totals first, then intersections.", "Use conditional formula as: required count / condition count.") + Doc.example("In a class, 18 like Maths, 12 like Physics, 8 like both. If a student likes Maths, P(likes Physics)?", "Condition count = Maths = 18. Intersection = both = 8. So P(Physics|Maths) = 8/18 = <strong>4/9</strong>.") + "<h4>Bayes idea (reverse conditioning)</h4>" + Doc.formula("P(A|B) = P(B|A)P(A) / P(B)") + "<p>Bayes is useful when tests are imperfect (false positives/false negatives). It helps answer: \u2018now that test is positive, what is the real chance of disease?\u2019</p>" + Doc.tip("For conditional probability, rewrite the sample space first: 'given B' means your new total is B.") + Doc.warn("Don't confuse P(A|B) with P(B|A). They are usually different.") + Doc.recap("Conditional probability narrows the sample space to what is known. Bayes flips the condition when needed."), 4));
        t.addQuestion(Doc.q("A fair die is rolled. P(getting an even number) is:", List.of("1/3", "1/2", "1/6", "2/3"), 1, "Even numbers {2,4,6} = 3 of 6 outcomes = 1/2.", "EASY"));
        t.addQuestion(Doc.q("A card is drawn from 52. P(it is a king) is:", List.of("1/13", "1/26", "1/4", "4/13"), 0, "4 kings / 52 = 1/13.", "EASY"));
        t.addQuestion(Doc.q("Two coins are tossed. P(at least one head) is:", List.of("1/4", "1/2", "3/4", "1"), 2, "P(no head) = 1/4, so P(at least one) = 1 - 1/4 = 3/4 (complement trick).", "MEDIUM"));
        t.addQuestion(Doc.q("A bag has 3 red and 2 blue balls. P(drawing a red) is:", List.of("2/5", "3/5", "1/2", "3/2"), 1, "3 red of 5 total = 3/5.", "EASY"));
        String ref = Doc.reference("For clean probability strategies see <em>Manhattan Prep GRE 5 lb. Book</em> (probability set) and <em>Arun Sharma \u2013 Quantitative Aptitude for the CAT</em> plus <em>Nishit K. Sinha</em> for mixed-event problems.");
        String wp = "<p>Probability stories are counting problems in disguise.</p>" + Doc.steps("List the sample space carefully and ensure outcomes are equally likely.", "Compute favourable and total counts, then simplify.", "Use complement for 'at least one' and conditional formula when extra information is given.") + Doc.tip("If replacement is not mentioned, draws are usually without replacement \u2014 probabilities change after each draw.");
        Enrich.lesson(t, 0, "prob-basics", ref, wp);
        Enrich.lesson(t, 1, "prob-complement", ref, wp);
        Enrich.lesson(t, 2, "prob-and-or", ref, wp);
        Enrich.lesson(t, 3, "prob-conditional", ref, wp);
        return t;
    }
}

