/*
 * Decompiled with CFR 0.152.
 */
package com.gremath.content;

import com.gremath.content.Doc;
import com.gremath.content.Enrich;
import com.gremath.content.TopicContent;
import com.gremath.model.Lesson;
import com.gremath.model.Topic;
import java.util.List;

public class ProfitInterestContent
implements TopicContent {
    @Override
    public Topic build() {
        Topic t = new Topic("profit-loss-interest", "Profit, Loss & Interest", "The maths of money: cost vs selling price, profit and loss percent, and how savings grow with simple and compound interest.", "BOTH", 10);
        t.addLesson(new Lesson("1. Cost price, selling price, profit & loss", "<p>Two prices matter when you buy and sell something:</p><ul><li><strong>Cost Price (CP)</strong> \u2014 what you paid to get it.</li><li><strong>Selling Price (SP)</strong> \u2014 what you sold it for.</li></ul>" + Doc.analogy("You buy a cricket bat for 200 (CP) and later sell it to a friend for 250 (SP). You're 50 better off \u2014 that 50 is your profit.") + Doc.formula("Profit = SP \u2212 CP &nbsp;&nbsp;&nbsp; Loss = CP \u2212 SP") + "<p>If SP is bigger, it's a profit; if CP is bigger, it's a loss.</p>" + Doc.recap("CP = price paid, SP = price sold for. Profit = SP \u2212 CP; Loss = CP \u2212 SP."), 1));
        t.addLesson(new Lesson("2. Profit % and loss % (always on cost price)", "<p>To compare deals fairly, we turn profit or loss into a percentage \u2014 and the base is <strong>always the cost price</strong>, unless a question clearly says otherwise.</p>" + Doc.formula("Profit % = (Profit \u00f7 CP) \u00d7 100 &nbsp;&nbsp;&nbsp; Loss % = (Loss \u00f7 CP) \u00d7 100") + Doc.key("Percentages here are measured on the <strong>cost price</strong>, because that's the money you actually put at risk.") + Doc.example("Buy at 200, sell at 250", "Profit = 50. Profit % = (50 \u00f7 200) \u00d7 100 = <strong>25%</strong>.") + Doc.example("Sell at a 10% loss on a 500 item", "Loss = 10% of 500 = 50. SP = 500 \u2212 50 = <strong>450</strong>.") + Doc.tip("Going from CP to SP, a profit of p% means SP = CP \u00d7 (1 + p/100); a loss of L% means SP = CP \u00d7 (1 \u2212 L/100).") + Doc.recap("Profit% and Loss% are taken on CP. Turn the percent into a multiplier to find SP quickly."), 2));
        t.addLesson(new Lesson("3. Simple interest", "<p><strong>Interest</strong> is the rent paid for borrowing money. With <strong>simple interest</strong>, you earn the same fixed amount every period, always based on the original sum (the <em>principal</em>).</p>" + Doc.formula("Simple Interest = (P \u00d7 R \u00d7 T) \u00f7 100") + "<p>P = principal, R = rate per year (%), T = time in years.</p>" + Doc.analogy("Lending a friend 1000 at 5% a year is like charging 50 \u2018rent\u2019 each year. After 3 years that's 50 + 50 + 50 = 150 \u2014 the same each year.") + Doc.example("SI on 1000 at 5% for 3 years", "SI = (1000 \u00d7 5 \u00d7 3) \u00f7 100 = <strong>150</strong>. Total to repay = 1000 + 150 = 1150.") + Doc.recap("Simple interest is the same each year: P\u00d7R\u00d7T\u00f7100, always on the original principal."), 3));
        t.addLesson(new Lesson("4. Compound interest", "<p>With <strong>compound interest</strong>, each period's interest is added to the principal, so the next period you earn <em>interest on interest</em>. Money snowballs.</p>" + Doc.formula("Amount = P \u00d7 (1 + R/100)^T") + "<p>Unlike simple interest (same gain every year), compound interest grows by a percentage of an ever-increasing base. So the absolute increase per year keeps rising.</p>" + Doc.analogy("A snowball rolling downhill picks up more snow because it's already bigger. Compound interest grows your money the same way \u2014 faster and faster over time.") + Doc.example("2000 at 10% per year for 2 years", "Year 1: 2000 + 10% = 2200. Year 2: 2200 + 10% = 2420. Using the formula: 2000 \u00d7 (1.1)\u00b2 = 2000 \u00d7 1.21 = <strong>2420</strong>.") + Doc.example("Compare SI vs CI quickly", "On 10,000 at 10% for 2 years:<br>SI amount = 10,000 + 2,000 = 12,000.<br>CI amount = 10,000\u00d71.1\u00b2 = 12,100.<br>Difference = <strong>100</strong> from interest-on-interest.") + "<h4>Compounded more than once per year</h4><p>If compounding is half-yearly, quarterly, etc., adjust both rate and periods.</p>" + Doc.formula("Amount = P \u00d7 (1 + r/m)^(mT)   where r = annual rate in decimal, m = compounds/year") + Doc.steps("Convert annual % to decimal r.", "Set m (2 for half-yearly, 4 for quarterly).", "Use rate per period r/m and total periods mT.") + Doc.warn("Compared with simple interest, compounding always gives <em>more</em> (here 420 vs 400), and the gap widens the longer the money is invested.") + Doc.tip("\u2018Per annum compounded annually\u2019 means once a year. If compounded twice a year, halve the rate and double the number of periods.") + Doc.recap("Compound interest pays interest on past interest: Amount = P(1 + R/100)^T. It beats simple interest over time."), 4));
        t.addLesson(new Lesson("5. Discounts, marked price and successive changes", "<p>In shopping questions, you often see a <strong>marked price (MP)</strong> and one or more discounts.</p>" + Doc.formula("Selling Price = Marked Price \u00d7 (1 \u2212 discount%/100)") + Doc.analogy("A 20% discount means you pay 80% of the tag price, not tag minus 20 rupees.") + "<h4>Successive discounts are multiplicative</h4><p>A 20% discount followed by 10% is not 30% off. It is 0.8 \u00d7 0.9 = 0.72 of MP, i.e. 28% off.</p>" + Doc.example("MP = 1000, discounts 20% then 10%", "SP = 1000 \u00d7 0.8 \u00d7 0.9 = <strong>720</strong>. Net discount = 280 = 28%.") + Doc.tip("Convert every percent change into a multiplier (1 \u00b1 p/100), then multiply. This avoids most mistakes.") + Doc.recap("For discounts and repeated changes, multiply percentage factors; don't directly add or subtract percentages."), 5));
        t.addQuestion(Doc.q("An item costs 200 and sells for 250. The profit percent is:", List.of("20%", "25%", "50%", "15%"), 1, "Profit = 50 on CP 200 = 25%.", "EASY"));
        t.addQuestion(Doc.q("Simple interest on 1000 at 5% per year for 3 years is:", List.of("100", "150", "200", "50"), 1, "SI = 1000\u00d75\u00d73/100 = 150.", "EASY"));
        t.addQuestion(Doc.q("An article bought for 500 is sold at a 10% loss. The selling price is:", List.of("450", "550", "490", "460"), 0, "Loss = 10% of 500 = 50, SP = 500 - 50 = 450.", "EASY"));
        t.addQuestion(Doc.q("The compound amount on 2000 at 10% per annum for 2 years is:", List.of("2400", "2420", "2200", "2410"), 1, "2000\u00d7(1.1)\u00b2 = 2000\u00d71.21 = 2420.", "MEDIUM"));
        String ref = Doc.reference("For business-math applications see <em>Arun Sharma \u2013 Quantitative Aptitude for the CAT</em>, <em>Nishit K. Sinha</em>, and GRE-style rate questions in <em>ETS Official Guide Quant</em>.");
        String wp = "<p>Money questions are mostly percentage-factor questions.</p>" + Doc.steps("Define CP, SP, MP, principal, rate, time clearly before calculating.", "Convert percentages to multipliers like 1.12 or 0.9.", "For multi-step changes (discount then tax, two discounts, etc.), multiply factors in order.") + Doc.tip("Profit/Loss percent is usually on CP; if a question uses SP or MP as base, it will explicitly say so.");
        Enrich.lesson(t, 0, "pli-cp-sp", ref, wp);
        Enrich.lesson(t, 1, "pli-profit-loss-pct", ref, wp);
        Enrich.lesson(t, 2, "pli-simple-interest", ref, wp);
        Enrich.lesson(t, 3, "pli-compound-interest", ref, wp);
        Enrich.lesson(t, 4, "pli-discount", ref, wp);
        return t;
    }
}

