/*
 * Decompiled with CFR 0.152.
 */
package com.gremath.content;

import com.gremath.content.Doc;
import com.gremath.content.Enrich;
import com.gremath.content.TopicContent;
import com.gremath.model.Lesson;
import com.gremath.model.Topic;
import java.util.List;

public class RatiosContent
implements TopicContent {
    @Override
    public Topic build() {
        Topic t = new Topic("ratios-proportions", "Ratios & Proportions", "How to compare amounts fairly: reading and simplifying ratios, splitting things in a ratio, chaining ratios, and direct vs inverse proportion.", "BOTH", 3);
        t.addLesson(new Lesson("1. What is a ratio?", "<p>A <strong>ratio</strong> compares two amounts by showing how many of one there are for each of the other. We write it with a colon, like <strong>2 : 3</strong> (say \u201ctwo to three\u201d).</p>" + Doc.analogy("A juice recipe says \u201c2 cups of mango for every 3 cups of water\u201d. That's the ratio 2 : 3. It doesn't fix the total \u2014 you could make a small jug (2 and 3) or a big one (20 and 30); the <em>taste</em> stays the same because the ratio is the same.") + "<h4>Ratios are like fractions in disguise</h4><p>The ratio 2 : 3 behaves just like the fraction 2/3, so you can <strong>scale it up or down</strong> by multiplying or dividing both sides by the same number:</p>" + Doc.formula("2 : 3 = 4 : 6 = 10 : 15 = 20 : 30") + "<h4>Simplifying a ratio</h4><p>Divide both numbers by their HCF to get the simplest form, just like reducing a fraction.</p>" + Doc.example("Simplify 18 : 24", "The HCF of 18 and 24 is 6. Divide both: 18\u00f76 : 24\u00f76 = <strong>3 : 4</strong>.") + Doc.warn("Units must match before you compare. A ratio of 1 metre to 50 cm is <strong>not</strong> 1 : 50 \u2014 convert first: 100 cm : 50 cm = 2 : 1.") + Doc.recap("A ratio compares amounts and can be scaled freely. Simplify by dividing both parts by their HCF."), 1));
        t.addLesson(new Lesson("2. Splitting a quantity in a given ratio", "<p>This is the everyday use of ratios: sharing money, sweets or work \u201cin the ratio a : b\u201d.</p><h4>The total-parts trick</h4>" + Doc.steps("Add the ratio numbers to get the <strong>total number of parts</strong>.", "Divide the quantity by the total parts to find the <strong>size of one part</strong>.", "Multiply each ratio number by the size of one part.") + Doc.example("Share 90 sweets in the ratio 2 : 3", "Total parts = 2 + 3 = 5. One part = 90 \u00f7 5 = 18 sweets. Shares = 2\u00d718 = <strong>36</strong> and 3\u00d718 = <strong>54</strong>. Check: 36 + 54 = 90 \u2713") + Doc.analogy("Think of the ratio as a number of identical buckets: 2 buckets for one person, 3 for the other \u2014 5 buckets in all. Pour the total evenly into the 5 buckets, then hand them out.") + Doc.tip("Always add up the shares at the end to confirm they make the original total. It catches arithmetic slips instantly.") + Doc.recap("Add the parts, find one part, then scale each share. Verify the shares sum to the total."), 2));
        t.addLesson(new Lesson("3. Chaining ratios together", "<p>Sometimes you're told a : b and b : c separately and must find a : c. The trick is to make the shared letter (b) the <strong>same number</strong> in both.</p>" + Doc.example("a : b = 2 : 3 and b : c = 4 : 5. Find a : c.", "b is 3 in the first and 4 in the second. Make both 12 (the LCM): scale the first by 4 \u2192 8 : 12, and the second by 3 \u2192 12 : 15. Now b matches, so a : b : c = 8 : 12 : 15, giving <strong>a : c = 8 : 15</strong>.") + Doc.analogy("It's like swapping currencies: if 1 apple = 3 coins and 4 coins = 5 berries, you make the \u2018coins\u2019 match on both sides before comparing apples to berries.") + Doc.tip("Make the common term equal to the LCM of its two values \u2014 it keeps the numbers whole and small.") + Doc.recap("To chain ratios, scale them so the shared term is identical, then read off the combined ratio."), 3));
        t.addLesson(new Lesson("4. Proportion: direct vs inverse", "<p>A <strong>proportion</strong> says two ratios are equal, e.g. a/b = c/d. From it we get the famous <strong>cross-multiplication</strong>:</p>" + Doc.formula("a/b = c/d &nbsp; \u27f9 &nbsp; a \u00d7 d = b \u00d7 c") + "<p>Use cross-multiplication only when two complete ratios are equal. It is a tool for solving unknowns, not for comparing unrelated numbers.</p><h4>Direct proportion \u2014 grow together</h4><p>When one amount doubles, the other doubles too. More items cost more money.</p>" + Doc.analogy("If 1 chocolate costs 20, then 3 chocolates cost 60. Cost goes up <em>in step</em> with quantity \u2014 that's direct proportion.") + Doc.formula("Direct: y = k \u00d7 x &nbsp; (the ratio y/x stays constant)") + Doc.example("Fuel and distance (constant mileage)", "If a bike gives 40 km per litre, then 3 litres gives 120 km and 5 litres gives 200 km. Distance grows directly with litres.") + "<h4>Inverse proportion \u2014 see-saw</h4><p>When one amount goes up, the other goes <em>down</em>, so their product stays the same.</p>" + Doc.analogy("More workers finish a job faster. If you double the workers, the time halves \u2014 like a see-saw: one side up, the other down.") + Doc.formula("Inverse: x \u00d7 y = k &nbsp; (the product stays constant)") + Doc.example("Speed-time with fixed distance", "If a route takes 4 hours at 60 km/h, then at 80 km/h time becomes 3 hours because speed\u00d7time is fixed (240).") + Doc.example("12 workers build a wall in 10 days. How long for 8 workers?", "Work is fixed, so workers \u00d7 days is constant: 12\u00d710 = 120. With 8 workers: days = 120 \u00f7 8 = <strong>15 days</strong> (fewer workers \u2192 more time).") + "<h4>Fast decision test</h4>" + Doc.steps("Ask: if input increases, should output increase (direct) or decrease (inverse)?", "For direct, keep ratio y/x constant. For inverse, keep product xy constant.", "After solving, do a reason check: does the answer move in the expected direction?") + Doc.warn("Decide direct or inverse <em>before</em> calculating. Ask: \u201cif this goes up, should the other go up (direct) or down (inverse)?\u201d") + Doc.recap("Proportion = equal ratios (cross-multiply). Direct: ratio constant. Inverse: product constant."), 4));
        t.addLesson(new Lesson("5. Partnership: sharing profit fairly", "<p>When friends start a business together, the profit is shared <strong>in the ratio of how much each one contributes</strong>. If they invest for different lengths of time, we use <em>money &times; time</em>.</p>" + Doc.analogy("Think of a shared lemonade stand: if you put in twice as much money as your friend, you should get twice the profit. Fair shares follow the ratio of contributions.") + "<h4>Simple case (same time period)</h4><p>Profit is split in the ratio of the amounts invested.</p>" + Doc.example("A invests 3000, B invests 2000, profit is 1000", "Ratio = 3000 : 2000 = 3 : 2 (5 parts). One part = 1000 \u00f7 5 = 200. A gets 3\u00d7200 = <strong>600</strong>, B gets 2\u00d7200 = <strong>400</strong>.") + "<h4>Different time periods</h4>" + Doc.formula("share ratio = (money\u2081 \u00d7 months\u2081) : (money\u2082 \u00d7 months\u2082)") + Doc.tip("Always reduce the contribution ratio first \u2014 smaller numbers make the share-out easier.") + Doc.recap("Profit is divided in the ratio of contributions; with unequal time, use money \u00d7 time."), 5));
        t.addQuestion(Doc.q("Simplify the ratio 18 : 24.", List.of("2 : 3", "3 : 4", "4 : 5", "6 : 7"), 1, "Divide both by their HCF 6: 18/6 : 24/6 = 3 : 4.", "EASY"));
        t.addQuestion(Doc.q("Divide 90 in the ratio 2 : 3. The larger share is:", List.of("36", "54", "45", "60"), 1, "Total parts = 5, each part = 18. Larger share = 3\u00d718 = 54.", "EASY"));
        t.addQuestion(Doc.q("If a : b = 2 : 3 and b : c = 4 : 5, then a : c is:", List.of("8 : 15", "2 : 5", "5 : 8", "3 : 5"), 0, "Make b common: a:b = 8:12, b:c = 12:15, so a:c = 8:15.", "MEDIUM"));
        t.addQuestion(Doc.q("12 workers build a wall in 10 days. How many days for 8 workers (inverse proportion)?", List.of("15", "12", "20", "6.7"), 0, "Work is constant: 12\u00d710 = 8\u00d7d \u2192 d = 120/8 = 15 days.", "MEDIUM"));
        String ref = Doc.reference("For deeper practice see <em>Manhattan Prep GRE Fractions, Decimals &amp; Percents</em> (ratios chapter) and, for CAT, <em>Sarvesh K. Verma \u2013 Quantum CAT</em> (Arihant) and <em>Arun Sharma \u2013 Quantitative Aptitude for the CAT</em>.");
        String wp = "<p>Ratio word problems give you a ratio plus one real number; your job is to find the value of one 'part'.</p>" + Doc.steps("Add the ratio numbers to get the total parts.", "Match the given real quantity to its parts to find the value of <strong>one part</strong>.", "Multiply to get any share you need; check the shares add back to the total.") + Doc.tip("If two ratios share a quantity (a:b and b:c), make the common term equal before combining.");
        Enrich.lesson(t, 0, "ratio-basics", ref, wp);
        Enrich.lesson(t, 1, "ratio-split", ref, wp);
        Enrich.lesson(t, 2, "ratio-chain", ref, wp);
        Enrich.lesson(t, 3, "ratio-proportion", ref, wp);
        Enrich.lesson(t, 4, "ratio-partnership", ref, wp);
        return t;
    }
}

