/*
 * Decompiled with CFR 0.152.
 */
package com.gremath.content;

import com.gremath.content.Doc;
import com.gremath.content.Enrich;
import com.gremath.content.TopicContent;
import com.gremath.model.Lesson;
import com.gremath.model.Topic;
import java.util.List;

public class TimeSpeedDistanceContent
implements TopicContent {
    @Override
    public Topic build() {
        Topic t = new Topic("time-speed-distance", "Time, Speed & Distance", "One simple triangle of ideas powers a huge family of questions: the speed\u2013distance\u2013time link, unit conversion, average speed, and relative speed.", "BOTH", 7);
        t.addLesson(new Lesson("1. The one relationship behind everything", "<p>Speed tells you <em>how fast</em> \u2014 how much distance you cover in each unit of time.</p>" + Doc.formula("Distance = Speed \u00d7 Time") + "<p>From this single fact, two more pop out by rearranging:</p>" + Doc.formula("Speed = Distance \u00f7 Time &nbsp;&nbsp;&nbsp; Time = Distance \u00f7 Speed") + Doc.analogy("Picture a triangle with <strong>D</strong> on top and <strong>S</strong> and <strong>T</strong> below. Cover the one you want: cover D and you see S\u00d7T; cover S and you see D over T; cover T and you see D over S. The triangle remembers all three formulas for you.") + Doc.example("150 km in 3 hours", "Speed = Distance \u00f7 Time = 150 \u00f7 3 = <strong>50 km/h</strong>.") + Doc.warn("Keep units matched. If speed is in km per <em>hour</em>, time must be in <em>hours</em> (30 minutes = 0.5 hour, not 30).") + Doc.recap("Distance = Speed \u00d7 Time, and you can rearrange it for any one of the three."), 1));
        t.addLesson(new Lesson("2. Converting units (km/h \u2194 m/s)", "<p>Questions switch between kilometres-per-hour and metres-per-second, so know the conversion cold.</p>" + Doc.formula("km/h \u2192 m/s : multiply by 5/18 &nbsp;&nbsp;&nbsp; m/s \u2192 km/h : multiply by 18/5") + "<p>Where do 5 and 18 come from? 1 km = 1000 m and 1 hour = 3600 s, and 1000/3600 simplifies to 5/18.</p>" + Doc.example("Convert 72 km/h to m/s", "72 \u00d7 5/18 = (72/18) \u00d7 5 = 4 \u00d7 5 = <strong>20 m/s</strong>.") + Doc.tip("To remember which fraction: going to the <em>smaller</em> unit (m/s) gives a smaller number, so multiply by the smaller fraction 5/18.") + Doc.recap("\u00d75/18 to go km/h \u2192 m/s; \u00d718/5 to go back."), 2));
        t.addLesson(new Lesson("3. Average speed (a famous trap)", "<p>If you drive somewhere at one speed and back at another, your average speed is <strong>not</strong> the simple average of the two numbers \u2014 because you spend more time at the slower speed.</p>" + Doc.warn("For equal distances, do <em>not</em> just do (u+v)\u00f72. That over-counts the fast part.") + "<h4>The correct rule for equal distances</h4>" + Doc.formula("Average speed = 2uv \u00f7 (u + v) &nbsp; (the \u2018harmonic mean\u2019)") + Doc.example("Half the journey at 40 km/h, half at 60 km/h", "Average = (2 \u00d7 40 \u00d7 60) \u00f7 (40 + 60) = 4800 \u00f7 100 = <strong>48 km/h</strong> \u2014 less than the naive 50, because more time was spent going slowly.") + Doc.key("Average speed is always total distance \u00f7 total time. When in doubt, just compute those two totals.") + Doc.recap("Average speed = total distance \u00f7 total time. For equal distances it's 2uv/(u+v), not (u+v)/2."), 3));
        t.addLesson(new Lesson("4. Relative speed (two moving objects)", "<p>When two things move, what matters is their speed <em>relative to each other</em>.</p><ul><li><strong>Towards each other</strong> (or meeting): <span class='big-num'>add</span> the speeds.</li><li><strong>Same direction</strong> (one chasing the other): <span class='big-num'>subtract</span> the speeds.</li></ul>" + Doc.analogy("Walking toward a friend, you close the gap using <em>both</em> your speeds combined. Walking in the same direction, only the <em>difference</em> in speed changes the gap.") + Doc.example("Two trains 80 km apart move towards each other at 30 and 50 km/h", "Closing speed = 30 + 50 = 80 km/h. Time to meet = distance \u00f7 closing speed = 80 \u00f7 80 = <strong>1 hour</strong>.") + Doc.example("A car at 70 km/h chases one at 50 km/h with 40 km lead", "Relative speed = 70 \u2212 50 = 20 km/h. Catch-up time = 40 \u00f7 20 = <strong>2 hours</strong>.") + "<h4>Train crossing cases</h4><p>Passing-time questions are also relative speed questions where distance is the total object length crossed.</p>" + Doc.steps("Passing a pole: distance = train length.", "Passing a platform: distance = train length + platform length.", "Two trains opposite directions: add speeds; same direction: subtract speeds.") + Doc.warn("Keep units consistent before dividing (convert km/h to m/s when lengths are in metres).") + Doc.tip("Trains passing a pole: distance = length of the train. Passing a platform: distance = train length + platform length.") + Doc.recap("Add speeds when approaching, subtract when chasing. Then use distance \u00f7 relative speed for the time."), 4));
        t.addLesson(new Lesson("5. Boats and streams", "<p>A boat in a river is a perfect example of relative speed. The water itself moves, so the boat's real speed depends on whether it goes <em>with</em> the current or <em>against</em> it.</p>" + Doc.analogy("Walking on an airport travelator: walking the same way as the belt, you zoom along; walking against it, you crawl. The river current is the travelator.") + Doc.formula("Downstream speed = boat speed + stream speed") + Doc.formula("Upstream speed = boat speed \u2212 stream speed") + "<h4>Working backwards</h4><p>If you know the downstream (D) and upstream (U) speeds, you can recover both:</p>" + Doc.formula("Boat speed = (D + U) \u00f7 2 &nbsp;&nbsp; Stream speed = (D \u2212 U) \u00f7 2") + Doc.example("A boat does 18 km/h downstream and 12 km/h upstream", "Boat speed = (18 + 12)/2 = <strong>15 km/h</strong>; stream speed = (18 \u2212 12)/2 = <strong>3 km/h</strong>.") + Doc.tip("Downstream is always the faster (bigger) number \u2014 the current is helping you.") + Doc.recap("Down = boat + stream, Up = boat \u2212 stream. Boat = (D+U)/2, Stream = (D\u2212U)/2."), 5));
        t.addQuestion(Doc.q("A car travels 150 km in 3 hours. Its speed is:", List.of("45 km/h", "50 km/h", "60 km/h", "75 km/h"), 1, "Speed = 150/3 = 50 km/h.", "EASY"));
        t.addQuestion(Doc.q("Convert 72 km/h to m/s.", List.of("15 m/s", "20 m/s", "25 m/s", "30 m/s"), 1, "72 \u00d7 5/18 = 20 m/s.", "EASY"));
        t.addQuestion(Doc.q("A person covers half a journey at 40 km/h and half at 60 km/h. Average speed is:", List.of("50 km/h", "48 km/h", "52 km/h", "45 km/h"), 1, "Equal distances \u2192 2\u00d740\u00d760/(40+60) = 4800/100 = 48 km/h.", "HARD"));
        t.addQuestion(Doc.q("Two trains 80 km apart move towards each other at 30 and 50 km/h. They meet in:", List.of("1 hour", "1.5 hours", "2 hours", "0.5 hour"), 0, "Relative (closing) speed = 80 km/h, time = 80/80 = 1 hour.", "MEDIUM"));
        String ref = Doc.reference("For the classic train, boat and clock problems see <em>Arun Sharma \u2013 Quantitative Aptitude for the CAT</em> and <em>Sarvesh K. Verma \u2013 Quantum CAT</em>; <em>Manhattan Prep GRE Word Problems</em> covers rate problems for the GRE.");
        String wp = "<p>Every speed problem rests on one triangle: <strong>Distance = Speed \u00d7 Time</strong>.</p>" + Doc.steps("Write down which two of {distance, speed, time} you know.", "Keep units consistent (convert km/h \u2194 m/s with \u00d75/18 or \u00d718/5).", "For two movers, add speeds if approaching and subtract if chasing or going upstream.") + Doc.tip("Average speed for equal distances is NOT the simple average \u2014 use 2ab/(a+b).");
        Enrich.lesson(t, 0, "tsd-basics", ref, wp);
        Enrich.lesson(t, 1, "tsd-units", ref, wp);
        Enrich.lesson(t, 2, "tsd-average-speed", ref, wp);
        Enrich.lesson(t, 3, "tsd-relative", ref, wp);
        Enrich.lesson(t, 4, "tsd-boats", ref, wp);
        return t;
    }
}

